Cargo.toml
crates/sol-macro/doctests
crates/sol-macro/src/lib.rs

Release 0.2.0

---

README.md

I was very confused when I saw this repo. Took a while to find the relevant twitter threads and read through a dozen or so posts.

Explain alloy vs ethers-rs intention

---

crates/dyn-abi/src/value.rs

A doc error slipped through in #144 
fix it 💪

fix: doc in dyn-abi

---

README.md

doc: add parser to readme

---

README.md

docs: add licensing note to README.md

---

.github/CODEOWNERS
.github/ISSUE_TEMPLATE/BUG-FORM.yml
.github/ISSUE_TEMPLATE/FEATURE-FORM.yml

chore: remove remaining refs to rlp

---

crates/syn-solidity/src/item/contract.rs

chore: clippy

---

.github/workflows/ci.yml

ci: cache wasm job

---

release.toml

chore: add release.toml

---

Cargo.toml

chore: release v0.3.1

---

crates/dyn-abi/src/ty.rs
crates/dyn-abi/src/value.rs

[`ethabi::Token::type{,s}_check`](https://docs.rs/ethabi/latest/ethabi/token/enum.Token.html#method.type_check)

feat(dyn-abi): add match functions to value and doc aliases

---

crates/primitives/src/bits/fixed.rs
crates/primitives/src/bits/macros.rs

feat(primitives): more `FixedBytes<N>` <-> `[u8; N]` conversions

---

crates/primitives/Cargo.toml
crates/primitives/src/bits/macros.rs

fix: hex compatibility

---

Cargo.toml
crates/dyn-abi/Cargo.toml
crates/json-abi/Cargo.toml

clap@4.4.0 updated their MSRV to 1.70.
We build it as part of criterion for our benches.
Lock them to earlier version, impacts only benches

fix: MSRV tests

---

crates/dyn-abi/src/eip712/coerce.rs
crates/dyn-abi/src/eip712/parser.rs
crates/dyn-abi/src/eip712/resolver.rs
crates/dyn-abi/src/eip712/typed_data.rs
crates/dyn-abi/src/error.rs
crates/dyn-abi/src/ext/abi.rs
crates/dyn-abi/src/ext/mod.rs
crates/dyn-abi/src/lib.rs
crates/dyn-abi/src/resolve.rs
crates/dyn-abi/src/ty.rs
crates/dyn-abi/src/value.rs
crates/sol-types/src/errors.rs
crates/sol-types/src/lib.rs

Addresses #210. Follow-up to #227.
- `JsonAbiExt`, implemented for `Constructor`, `Error`, `Function`
- `FunctionExt`, implemented for `Function`
- new error variants; reduce size of error types

feat(dyn-abi): implement more ext traits for json-abi

---

crates/sol-types/src/types/struct.rs
crates/sol-types/tests/sol.rs

Close #257 
Remove extra keccak, add test

fix: struct `eip712_data_word`

---

crates/sol-macro/src/attr.rs
crates/sol-macro/src/expand/contract.rs
crates/sol-macro/src/expand/enum.rs
crates/sol-types/tests/sol.rs
crates/syn-solidity/src/item/enum.rs
crates/syn-solidity/src/item/mod.rs
crates/syn-solidity/src/lib.rs
crates/syn-solidity/src/macros.rs
crates/syn-solidity/src/spanned.rs

feat: add attributes to enum variants

---

.github/workflows/ci.yml
Cargo.toml
crates/dyn-abi/Cargo.toml
crates/json-abi/Cargo.toml
crates/json-abi/src/to_sol.rs

Fix dev deps bumping their msrv, which does not affect our crates
Run tests only on current stable and above

chore: fix MSRV CI and dev deps

---

crates/primitives/src/bytes/mod.rs

feat: impl `bytes::Buf` for our own `Bytes`

---

crates/primitives/src/lib.rs

chore: re-export ::bytes

---

crates/sol-macro/src/expand/contract.rs
crates/sol-types/src/lib.rs
crates/sol-types/src/types/error.rs
crates/sol-types/src/types/interface.rs
crates/sol-types/src/types/mod.rs

Improve `Panic`, `Revert` and impl Error;
Implement `SolInterface` for len 0 (by implementing it for `Infallible`), and len 1 (by lowering the threshold in `sol!`)

feat: improve `SolError`, `SolInterface` structs and implementations

---

crates/syn-solidity/README.md

docs(syn-solidity): document dollar signs in idents

---

crates/sol-macro/src/expand/mod.rs
crates/sol-macro/src/expand/ty.rs
crates/sol-macro/src/utils.rs

fix: respect `all_derives = false`, fix custom type printing

---

crates/dyn-abi/src/ext/abi.rs
crates/json-abi/src/param.rs
crates/json-abi/src/utils.rs
crates/primitives/src/aliases.rs
crates/primitives/src/bits/function.rs
crates/sol-type-parser/src/lib.rs

feat(primitives): add more methods to `Function`

---

crates/json-abi/src/item.rs
crates/json-abi/src/param.rs
crates/json-abi/src/utils.rs
crates/primitives/src/utils.rs

Signature with output/return types: `$name($($inputs),*)($(outputs),*)`

feat(json-abi): add `Function::signature_full`

---

.github/workflows/ci.yml
crates/sol-macro/src/expand/event.rs
crates/sol-macro/src/input.rs
crates/syn-solidity/src/attribute/function.rs
crates/syn-solidity/src/attribute/variable.rs
crates/syn-solidity/src/file.rs
crates/syn-solidity/src/ident/path.rs
crates/syn-solidity/src/lib.rs
crates/syn-solidity/src/lit/str.rs
crates/syn-solidity/src/spanned.rs
crates/syn-solidity/src/utils.rs
crates/syn-solidity/src/variable/list.rs
crates/syn-solidity/src/yul/ident/path.rs
crates/syn-solidity/src/yul/stmt/assignment.rs
crates/syn-solidity/src/yul/stmt/var_decl.rs

and improve existing ones
Remove some unneeded bounds and make use of slice and punctuated impls

feat(syn-solidity): add more `Spanned` impls

---

crates/syn-solidity/src/macros.rs

chore: touch up #314

---

crates/sol-macro/src/expand/enum.rs
crates/sol-macro/src/expand/struct.rs
crates/sol-types/tests/sol.rs

fix(sol-macro): implement EventTopic for generated enums

---

.github/workflows/ci.yml
crates/primitives/Cargo.toml

https://docs.rs/crate/alloy-primitives/0.4.1/builds/935180

fix(primitives): set serde derive feature

---

crates/sol-types/src/types/value.rs

Function docs were flipped around incorrectly
Correct them

docs(`alloy-sol-types`): Switch incorrect function docs

---

crates/sol-macro/Cargo.toml
crates/sol-macro/doctests
crates/sol-macro/doctests/README.md
crates/sol-macro/doctests/contracts.rs
crates/sol-macro/doctests/events.rs
crates/sol-macro/doctests/function_like.rs
crates/sol-macro/doctests/json.rs
crates/sol-macro/doctests/structs.rs
crates/sol-macro/doctests/types.rs

fix: don't use directory symlinks

---

crates/sol-types/tests/sol.rs
crates/syn-solidity/src/attribute/function.rs

fix(syn-solidity): allow some duplicate attributes

---

crates/dyn-abi/src/coerce.rs
crates/sol-types/src/abi/decoder.rs

Fixes https://github.com/foundry-rs/foundry/issues/6211

fix(dyn-abi): handle empty hex strings

---

crates/dyn-abi/src/coerce.rs

fix(dyn-abi): correctly parse strings in `coerce_str`

---

crates/sol-macro/src/expand/enum.rs

I found a bug which I open an issue in https://github.com/alloy-rs/core/issues/412
Closes #412
Directly casting pointer type

fix: wrong as_u8 generated for enum

---

crates/sol-macro/src/expand/mod.rs
crates/sol-macro/src/expand/struct.rs
crates/sol-macro/src/json.rs
crates/sol-types/Cargo.toml
crates/sol-types/tests/sol.rs
crates/sol-types/tests/ui/keywords.rs
crates/sol-types/tests/ui/keywords.stderr
crates/syn-solidity/src/ident/difference.expr
crates/syn-solidity/src/ident/intersection.expr
crates/syn-solidity/src/ident/kw.c
crates/syn-solidity/src/ident/mod.rs
crates/syn-solidity/tests/ident.rs

Clean up raw identifier handling

fix(syn-solidity): raw keyword identifiers

---

crates/dyn-abi/README.md
crates/dyn-abi/src/token.rs
crates/sol-macro/src/expand/enum.rs
crates/sol-macro/src/expand/error.rs
crates/sol-macro/src/expand/event.rs
crates/sol-macro/src/expand/function.rs
crates/sol-macro/src/expand/struct.rs
crates/sol-types/src/abi/decoder.rs
crates/sol-types/src/abi/encoder.rs
crates/sol-types/src/abi/mod.rs
crates/sol-types/src/abi/token.rs
crates/sol-types/src/errors.rs
crates/sol-types/src/lib.rs
crates/sol-types/src/types/data_type.rs
crates/sol-types/src/types/error.rs
crates/sol-types/src/types/event/mod.rs
crates/sol-types/src/types/event/topic_list.rs
crates/sol-types/src/types/function.rs
crates/sol-types/src/types/ty.rs
crates/sol-types/src/types/udt.rs
crates/sol-types/src/types/value.rs

Last few remaining breaking changes before 0.5.

chore: rename `TokenType` GAT and trait to `Token`

---

crates/json-abi/tests/abi.rs
crates/syn-solidity/src/item/function.rs

Fixes https://github.com/alloy-rs/core/issues/423
Parse version string and compare to needed version.

test: check version before running Solc

---

crates/primitives/src/lib.rs
crates/primitives/src/signed/int.rs
crates/primitives/src/utils/mod.rs
crates/primitives/src/utils/units.rs

Improve existing and add new utilities. Mostly the `units` utilities from ethers-core.

feat(primitives): improve utils

---

crates/sol-macro/src/expand/mod.rs

Anvil is currently not building on master. I'm not entirely sure how this crate is building, but would love to learn if someone has an explanation.
There's a simple leaked private type error. This fixes it by making the relevant struct public.
- [ n/a] Added Tests
- [ n/a] Added Documentation
- [n/a] Breaking changes

fix public leak

---

.github/workflows/ci.yml

ci: re-enable MSRV all features check

---

crates/sol-types/src/types/error.rs
crates/sol-types/src/types/interface/mod.rs

Avoid breaking change for a patch release. Initially added in #450.
Use String again as the return type of decode_revert_reason.

fix(sol-types): un-break decode revert

---

crates/sol-types/src/types/error.rs

chore(sol-types): make PanicKind non_exhaustive

---

crates/primitives/Cargo.toml

feat: enable postgres ruint feature

---

crates/primitives/src/utils/units.rs

feat(primitives): support parsing numbers in Unit::from_str

---

crates/primitives/src/lib.rs

feat(primitives): re-export ::bytes

---

crates/primitives/Cargo.toml
crates/primitives/benches/address.rs
crates/primitives/src/bits/address.rs

chore: clean up address checksum implementation

---

crates/sol-macro/src/expand/udt.rs

Nits after https://github.com/alloy-rs/core/pull/471

chore: touch up UDVT expansion

---

crates/dyn-abi/src/coerce.rs

https://t.me/foundry_support/48383

feat(dyn-abi): improve hex error messages

---

crates/dyn-abi/src/ty.rs
crates/primitives/src/bits/address.rs
crates/primitives/src/bits/bloom.rs
crates/primitives/src/bits/ssz.rs
crates/primitives/src/postgres.rs
crates/primitives/src/signature/error.rs
crates/primitives/src/signature/parity.rs
crates/primitives/src/signature/sig.rs
crates/primitives/src/utils/units.rs
crates/sol-types/src/types/interface/mod.rs
crates/syn-solidity/src/item/contract.rs
crates/syn-solidity/src/item/import.rs
crates/syn-solidity/src/yul/stmt/mod.rs

chore: clippy uninlined_format_args, use_self

---

crates/primitives/src/signature/parity.rs

docs: update docs on parity

---

crates/sol-types/tests/ui/keywords.stderr

chore: bless tests

---

Cargo.toml

We're using `decode_to_array` which was released in version `1.10.0`.

chore(deps): bump const-hex requirement

---

Cargo.toml
crates/primitives/Cargo.toml

chore(deps): relax k256 requirement

---

crates/json-abi/tests/abi.rs
crates/primitives/src/signature/sig.rs

chore(primitives): pass B256 by reference in Signature methods

---

crates/dyn-abi/src/coerce.rs
crates/sol-types/src/impl_core.rs

fix new doc issues that are breaking the build
update a link, cfg_attr a feature-specific line

doc: fixes

---

crates/dyn-abi/src/coerce.rs
crates/sol-types/src/impl_core.rs

https://github.com/alloy-rs/core/pull/498

docs: remove stray list element

---

crates/sol-macro/src/expand/contract.rs
crates/sol-types/src/types/interface/mod.rs

We already have a sorted list of all the selectors, use that instead of another big match expression

perf(sol-macro): use `binary_search` in `SolInterface::valid_selector`

---

crates/sol-macro/src/expand/contract.rs
crates/sol-macro/src/expand/to_abi.rs
crates/sol-macro/src/expand/var_def.rs
crates/sol-macro/src/lib.rs
crates/sol-types/tests/doctests/contracts.rs
crates/sol-types/tests/doctests/function_like.rs
crates/syn-solidity/src/item/function.rs

State variables were not included in contract's enums and other logic.

feat(sol-macro): expand state variable getters in contracts

---

Cargo.toml

Winnow was incremented in https://github.com/alloy-rs/core/pull/507

chore(deps): bump winnow

---

crates/sol-macro/src/expand/enum.rs
crates/sol-macro/src/expand/struct.rs
crates/sol-macro/src/expand/udt.rs
crates/sol-macro/src/verbatim.rs
crates/sol-types/src/errors.rs
crates/sol-types/src/types/data_type.rs
crates/sol-types/src/types/ty.rs
crates/sol-types/src/types/value.rs

Type names can be formatted at compile time.

feat(sol-types): constify type name formatting

---

crates/core/src/lib.rs

Use local crate reexport instead of extern crate

docs: update alloy_core::sol reference to real sol

---

crates/dyn-abi/src/coerce.rs
crates/sol-type-parser/src/utils.rs

Ref https://github.com/foundry-rs/foundry/issues/6998

test: add some more coerce error message tests

---

crates/dyn-abi/src/ext/abi.rs
crates/sol-types/src/abi/encoder.rs

https://github.com/foundry-rs/foundry/issues/7280

test: add another ABI encode test

---

crates/primitives/src/common.rs

Small helpers for https://github.com/alloy-rs/alloy/pull/361

small helpers for alloy serde PR

---

README.md

Same as https://github.com/alloy-rs/alloy/pull/537

docs: update README crate links to use URLs

---

crates/primitives/src/common.rs

missing arbitrary impl for TxKind

feat: add arbitrary for TxKind

---

crates/sol-macro/src/expand/contract.rs

Mutually dependent on, and unblocks https://github.com/alloy-rs/alloy/pull/553
use explicit deployment in the sol expansion

fix: use deploy in sol expansion

---

crates/primitives/src/utils/units.rs

Closes https://github.com/alloy-rs/core/issues/598.

feat(primitives): implement TryInto for ParseUnits

---

crates/json-abi/src/item.rs
crates/sol-macro-input/src/input.rs

Closes https://github.com/alloy-rs/core/issues/638.

chore(sol-macro): add suggestion to remove name

---

crates/primitives/src/signature/sig.rs

v value should be serialized as hex

fix: use quantity for v value

---

crates/sol-type-parser/src/error.rs
crates/sol-type-parser/src/input.rs

Temporary hotfix as the implementation is correct but errors anyway, see issue for more details.
Fixes https://github.com/alloy-rs/core/issues/717.

fix(sol-type-parser): winnow std error

---

crates/primitives/src/bits/macros.rs

docs(primitives): document features in `wrap_fixed_bytes`-generated types

---

crates/sol-macro-expander/src/expand/contract.rs
crates/sol-macro-expander/src/expand/mod.rs

Fixes lint warnings for `alloy-sol-macro-expander`.

Fix lint `alloy-sol-macro-expander`

---

crates/sol-types/src/abi/token.rs

Fixes lint warnings for `alloy-sol-types`.

Fix lint alloy-sol-types

---

crates/dyn-abi/src/dynamic/token.rs

Fixes lint warnings for `alloy-dyn-abi`.

Fix lint `alloy-dyn-abi`

---

.github/workflows/deps.yml
crates/sol-macro-expander/src/expand/var_def.rs
crates/syn-solidity/src/attribute/function.rs
crates/syn-solidity/src/attribute/variable.rs
crates/syn-solidity/src/type/mod.rs
crates/syn-solidity/src/yul/stmt/var_decl.rs
deny.toml

This will be reported on main or in a PR anyway.

ci: remove cron schedule for deps.yml

---

crates/sol-types/tests/macros/sol/mod.rs
crates/syn-solidity/src/expr/mod.rs
crates/syn-solidity/src/type/mod.rs

Fixes https://github.com/alloy-rs/core/issues/829

fix(syn-solidity): correctly parse invalid bytes* etc as custom

---

crates/core/Cargo.toml
crates/primitives/Cargo.toml

re-export `hashbrown` and `indexmap` `rayon` feature

feat: re-export `rayon` feature

---

crates/dyn-abi/src/coerce.rs
crates/sol-type-parser/src/input.rs

Ref https://github.com/foundry-rs/foundry/actions/runs/12597916137/job/35111802710?pr=9617

fix: coerce pow overflow

---

crates/sol-macro-expander/src/expand/ty.rs
crates/sol-types/tests/macros/sol/mod.rs

Closes https://github.com/alloy-rs/core/issues/347.

feat(sol-macro): translate contract types to address

---

crates/sol-types/tests/macros/sol/mod.rs

Refs https://github.com/alloy-rs/core/issues/599.

test(sol-macro): add a test for namespaced types

---

crates/sol-macro/src/lib.rs

Closes https://github.com/alloy-rs/core/issues/254.

docs(sol-macro): document visibility and state mutability

---

crates/primitives/src/hex_literal.rs
tests/core-sol/src/lib.rs

Unintentional breaking change.

fix(primitives): hex macro re-export

---

crates/primitives/src/sealed.rs

add helper for `&Sealed<T>` to `Sealed<&T>`

feat: add Sealed::as_sealed_ref

---

crates/primitives/README.md
crates/primitives/src/bits/bloom.rs
crates/primitives/src/bits/fixed.rs
crates/sol-types/src/utils.rs

docs: add more 0x to alloy-primitives readme example

---

crates/sol-types/src/types/interface/mod.rs

adds some helpers for the revertreason type

feat: add helpers for revertreason

---

crates/primitives/src/signature/primitive_sig.rs

Closes #891 
- Display hex-encoded bytes

feat(`primitives`): impl Display for PrimitiveSig

---

crates/sol-types/tests/macros/sol/mod.rs
tests/core-sol/src/lib.rs

Follow-up https://github.com/alloy-rs/core/pull/903.

test: move 'self' keyword test

---

crates/sol-macro-expander/src/expand/mod.rs
crates/sol-macro-input/src/attr.rs
crates/sol-macro/src/lib.rs
crates/sol-types/tests/macros/sol/mod.rs

Closes https://github.com/alloy-rs/core/issues/688.

feat(sol-macro): add `#![sol(extra_derives(...)]`

---

crates/primitives/src/utils/mod.rs
crates/primitives/src/utils/units.rs

feat: added standalone format_units_with

---

crates/sol-types/src/types/data_type.rs

- Consistency with other types
- I need it [here](https://github.com/makcandrov/sdecode/blob/606bbd8d3c503a084313896b1612a2611775bbb6/crates/sdecode-solidity/src/types.rs#L14)

remove unnecessary bound on `sol_data::Array`

---

crates/dyn-abi/Cargo.toml
crates/dyn-abi/src/arbitrary.rs
crates/dyn-abi/src/coerce.rs
crates/dyn-abi/src/eip712/coerce.rs
crates/dyn-abi/src/eip712/typed_data.rs
crates/dyn-abi/src/error.rs
crates/sol-types/Cargo.toml
crates/sol-types/src/abi/decoder.rs
crates/sol-types/src/abi/token.rs
crates/sol-types/src/errors.rs

chore: re-use alloy_primitives::hex

---

crates/json-abi/src/abi.rs

chore: add helper to find function by selector

---

crates/sol-types/README.md

chore: typo rollup

---

crates/primitives/src/lib.rs

Awareness for people trying to find stuff on docs.rs
Inline document the re-exported `uint!`. Closes #1006.

doc(primitives): inline doc for uint! macro
