alloy-rs/core

- .gitignore
- crates/sol-macro/src/expand/error.rs
- crates/sol-macro/src/expand/function.rs
- crates/sol-types/src/types/error.rs
- crates/sol-types/src/types/function.rs
closes https://github.com/alloy-rs/core/issues/91
"When you come to a fork in the road, take it." - Yogi Berra
checked with
```bash
cargo check --all-features
cargo +nightly fmt --all
cargo build --all-features
cargo test --all-features
cargo +nightly clippy --all-features
```
simple name change
> refactor: Rename Sol*::Tuple to Parameters/Arguments 

- .github/PULL_REQUEST_TEMPLATE.md
- CONTRIBUTING.md
Contributors so far have allowed edits, and neither PR would have gotten in quickly without it
Request all future contributors also allow edits
- [n/a] Added Tests
- [n/a] Breaking changes
> doc: request that PR contributors allow maintainer edits

- crates/primitives/README.md
Noticed broken crate link.
Found what I think is the correct crate and updated the link. Presumably this happened because of a name change.
Note: I read through the contribution guidelines, but feel free to lmk if there's anything I should've done in this PR that I didn't (I assume most things don't apply to trivial docs fixes).
> fix(alloy-primitives): fix broken documentation link

- crates/dyn-abi/README.md
- crates/dyn-abi/benches/abi.rs
- crates/dyn-abi/src/lib.rs
- crates/dyn-abi/src/token.rs
- crates/dyn-abi/src/type.rs
- crates/dyn-abi/src/value.rs
This PR brings dyn-abi to performance parity with ethabi (or better) on all benchmarks
It does this by
- removing unnecessary type checks during value encoding
- removing buffer copies during decoding into tokens
- bypassing tokenization during value encoding
Followup work may bypass decoding into tokens and decode directly into values
dyn-abi is slow and should be fast 😤 
make it faster
> Refactoring `dyn-abi` to performance parity with ethabi

- crates/primitives/src/bits/address.rs
- crates/primitives/src/bits/fixed.rs
- crates/primitives/src/bits/macros.rs
- crates/primitives/src/bytes/mod.rs
- crates/primitives/src/lib.rs
Encountered while migrating `revm` to `alloy-primitives`.
- `TryFrom` slices for `FixedBytes` and newtype macro, same as `core::array::TryFrom...`
- `Deref` to `bytes::Bytes` instead of directly to `[u8]`
> feat(primitives): add some impls

- crates/dyn-abi/src/type.rs
closes #165 
Missing function in API
Add the missing function :)
> feature: DynSolType::decode_params

- crates/dyn-abi/src/token.rs
Fixes #170
Remove a reachable and unnecessary unwrap in `decode_populate`.
> fix: remove unwrap in decode_populate

- crates/dyn-abi/Cargo.toml
- crates/dyn-abi/src/eip712/coerce.rs
- crates/dyn-abi/src/error.rs
- crates/dyn-abi/src/lib.rs
- crates/dyn-abi/src/type.rs
> chore(dyn-abi): gate eip712 behind a feature

- crates/dyn-abi/benches/abi.rs
- crates/rlp/README.md
- crates/rlp/src/lib.rs
Can `cfg` inside of the example instead of conditionally adding it to the inline docs with `cfg_attr`
> docs(rlp): move example to README.md

- crates/dyn-abi/Cargo.toml
- crates/dyn-abi/src/eip712/coerce.rs
- crates/dyn-abi/src/eip712/mod.rs
- crates/dyn-abi/src/eip712/parser.rs
- crates/dyn-abi/src/eip712/resolver.rs
- crates/dyn-abi/src/eip712/typed_data.rs
- crates/dyn-abi/src/lib.rs
- crates/dyn-abi/src/parser.rs
- crates/dyn-abi/src/token.rs
- crates/dyn-abi/src/type.rs
- crates/dyn-abi/src/value.rs
- crates/sol-types/src/coder/encoder.rs
Cfg EIP-712 specific `CustomStruct`, and remove unused `CustomValue` variants from the `dyn-abi` enums.
> feat(dyn-abi): cfg CustomStruct for eip712, rm CustomValue

- crates/primitives/src/bits/macros.rs
- crates/primitives/src/bits/rlp.rs
- crates/primitives/src/bytes/rlp.rs
- crates/rlp-derive/src/de.rs
- crates/rlp-derive/src/en.rs
- crates/rlp-derive/src/utils.rs
- crates/rlp/Cargo.toml
- crates/rlp/src/decode.rs
- crates/rlp/src/encode.rs
- crates/rlp/src/error.rs
- crates/rlp/src/header.rs
- crates/rlp/src/lib.rs
- crates/rlp/tests/derive.rs
Refactor decode and add new impls and features.
Preferably `Decodable` would have a `'de` lifetime, and `Decodable::decode`'s param would be a `&mut Decoder<'de>` struct which would allow for easier helper method access (like `Header::decode` -> `d.decode_header()?;` etc), and deserializing borrowed byte and string slices, but this would be a significant breaking change so I didn't implement this here.
- dedup decoding code by adding more static methods to `Header`, and by refactoring `Header::decode` to use a match expression.
- add `smol_str` dep + feature from `reth-rlp`
- add `arrayvec` impls + gate `encode_fixed_size` function to feature
- breaking changes to the free-standing `encode_*` functions' generics
- un-`#[doc(hide)]` and document `MaxEncodedLen`, `MaxEncodedLenAssoc`
- add …
> feat/refactor(rlp): improve implementations

- Cargo.toml
- crates/primitives/Cargo.toml
- crates/primitives/src/utils.rs
As outlined in Paradigm's [introduction of Alloy](https://www.paradigm.xyz/2023/06/alloy), avoiding fragmentation of the Rust ecosystem on Ethereum means that everyone should use a consistent set of primitive types. As Rust expands into new Ethereum domains like smart contract development, generality will be key for this shared dependency.
The [`alloy_primatives`](https://docs.rs/alloy-primitives/latest/alloy_primitives/) crate included here does this very well, but could be made even better for upcoming Rust-enabled Ethereum smart contract environments like [Arbitrum Stylus](https://offchain.medium.com/hello-stylus-6b18fecc3a22). 
In addition to providing types, the crate currently pulls in `tiny_keccak`. This makes sense for most existing platforms, but in code running on top of VMs …
> feat: native keccak feature flag

- crates/sol-macro/src/expand/struct.rs
- crates/sol-types/src/types/struct.rs
`SolStruct::eip712_encode_type` is incorrect and always overridden by sol macro.
We remove it
> fix: remove unused method body on solstruct

- Cargo.toml
- crates/dyn-abi/src/arbitrary.rs
~~Requires recmo/uint#264 + `ruint` release~~
> chore: replace `ruint2` with `ruint`

- crates/primitives/src/bytes/mod.rs
Calling these methods would return `bytes::Bytes` instead of `alloy_primitives::Bytes`
> chore: wrap Bytes methods which return Self

- README.md
- crates/json-abi/Cargo.toml
- crates/json-abi/README.md
- crates/json-abi/src/lib.rs
Because it's missing, same as other crates.
> docs(json-abi): add README.md

- crates/sol-types/src/types/ty.rs
Conversation in telegram
- Adds ambiguity details and recommendations to the `Encodable<T: SolType>` trait docs
- Adds a `sol_type_name` passthrough function to `Encodable<T: SolType>` for convenience wrt unambiguous types
- [no] Breaking changes
> docs: add ambiguity details to Encodable rustdoc

- Cargo.toml
- crates/json-abi/Cargo.toml
- crates/json-abi/src/abi.rs
- crates/json-abi/src/internal_type.rs
- crates/json-abi/tests/test.rs
Fixes https://github.com/alloy-rs/core/issues/101
~Struggling to write tests for `load` method from `ethabi`~ 
Thanks @prestwich for the help!
Reference from methods from `ethabi`
> feat: support `ethabi` Contract methods

- Cargo.toml
Alloy use of ruint broken in 1.10.0
Closes #212
This depends on release of ruint @ 1.10.1
> chore: bump ruint to 1.10.1 + alloc

- README.md
ruint `no_std` is live!
Closes #214 
Update readme note
> doc: update no-std not in readme

- crates/sol-macro/src/expand/function.rs
- crates/sol-macro/src/expand/mod.rs
- crates/syn-solidity/src/item/function.rs
Fixes #184 
Ref #157, this just avoids panicking and doesn't generate anything. We would need to support fallbacks and receive functions as separate structs in sol-type but I'm not sure if this is that useful. cc @prestwich
> fix(sol-macro): don't panic when encountering functions without names

- Cargo.toml
- crates/json-abi/src/abi.rs
- crates/sol-macro/src/expand/contract.rs
- crates/sol-macro/src/expand/mod.rs
- crates/sol-macro/src/expand/struct.rs
- crates/sol-macro/src/expand/ty.rs
- crates/sol-macro/src/expand/udt.rs
- crates/sol-macro/src/json.rs
- crates/sol-types/tests/sol.rs
- crates/syn-solidity/Cargo.toml
- crates/syn-solidity/src/attribute/function.rs
- crates/syn-solidity/src/attribute/variable.rs
- crates/syn-solidity/src/item/error.rs
- crates/syn-solidity/src/item/function.rs
- crates/syn-solidity/src/item/mod.rs
- crates/syn-solidity/src/item/struct.rs
- crates/syn-solidity/src/lib.rs
- crates/syn-solidity/src/macros.rs
- crates/syn-solidity/src/type/function.rs
- crates/syn-solidity/src/variable/list.rs
- crates/syn-solidity/src/variable/mod.rs
Closes #125
Insert an `ItemFunction` for each state variable/constant that is either public or external.
This has to be added in the AST because we also handle function overloads etc before expansion.
> feat(sol-macro): expand getter functions for public state variables

- crates/dyn-abi/src/eip712/resolver.rs
- crates/sol-macro/src/expand/struct.rs
- crates/sol-types/src/types/data_type.rs
- crates/sol-types/src/types/struct.rs
- crates/sol-types/src/types/udt.rs
- crates/sol-types/tests/sol.rs
- crates/syn-solidity/src/type/mod.rs
Fixes #219
Check for `UDVT`s when computing struct eip712 root type and signature.
Also implement `EventTopic` for `UDVT`s declared with the macro, as it is also needed.
> fix(sol-macro): encode UDVTs as their underlying type in EIP-712

- Cargo.toml
- crates/primitives/Cargo.toml
- crates/primitives/src/bits/serde.rs
- crates/primitives/src/bytes/serde.rs
Fixes `bincode` deserialization of `FixedBytes` and `Bytes`.
Distinguish between `is_human_readable` and not also in the deserialization. If it is not human readable (e.g. `bincode`) allow only bytes instead of also strings.
This fixes #221 .
Added tests for the `bincode` roundtrip that previously failed.
> fix bincode serialization

- crates/dyn-abi/src/eip712/resolver.rs
- crates/dyn-abi/src/eip712/typed_data.rs
- crates/sol-types/src/eip712.rs
- crates/sol-types/src/macros.rs
Minor improvement to the `eip712_domain!` macro.
If an `expr` is a `literal`, then use `Cow::Borrowed`, else use `Cow::from`.
> feat(dyn-abi): allow `T: Into<Cow<str>>` in `eip712_domain!`

- crates/sol-macro/src/expand/contract.rs
- crates/sol-types/tests/sol.rs
`heck` doesn't treat numbers as new words, and discards leading underscores, thus:
```solidity
contract C {
function f();
function _f();
}
```
failed to compile because the generated `is_`... functions would have the same name for both variants.
Create a helper function for snakifying idents, taken from [`strum`](https://github.com/Peternator7/strum/blob/fcb9841a744543b993eb1645db35dbda541e9a30/strum_macros/src/macros/enum_is.rs#L48C1-L61C2)
> fix(sol-macro): snake_case'd function names

- crates/dyn-abi/src/arbitrary.rs
- crates/dyn-abi/src/eip712/coerce.rs
- crates/dyn-abi/src/resolve.rs
- crates/dyn-abi/src/ty.rs
- crates/dyn-abi/src/value.rs
- crates/primitives/src/bits/address.rs
- crates/primitives/src/bits/function.rs
- crates/primitives/src/bits/mod.rs
- crates/primitives/src/lib.rs
- crates/sol-macro/src/expand/ty.rs
- crates/sol-type-parser/src/root.rs
- crates/sol-types/src/types/data_type.rs
- crates/sol-types/src/types/event/topic.rs
- crates/sol-types/tests/ui/type.rs
- crates/sol-types/tests/ui/type.stderr
- crates/syn-solidity/src/attribute/function.rs
- crates/syn-solidity/src/type/mapping.rs
Closes #127
Adds a `Function`:
- a new-type in primitives (bytes24)
- an enum variant in dyn-abi type and value
and add parsing in sol-macro and sol-types
> feat: function type

- crates/dyn-abi/src/token.rs
- crates/json-abi/src/abi.rs
- crates/primitives/src/bits/serde.rs
- crates/sol-types/src/coder/encoder.rs
- crates/sol-types/src/types/data_type.rs
- crates/sol-types/src/utils.rs
- `try_for_each` generally generates more llvm-ir and tends to be less optimized than just loop with `?`
- rest of changes are commented below individually
> perf: optimize some stuff

- crates/dyn-abi/Cargo.toml
- crates/dyn-abi/src/resolve.rs
- crates/json-abi/Cargo.toml
Added support for Function input encoding and output decoding.  This is in reference to issue #210 
Added trait `FunctionExt` that defines 2 methods: `encode_input(...)` and `decode_output(...)` and an implementation of the trait for `json_abi::Function`.  Currently this resides in `resolve.rs`.
> feat: Add support for function input/output encoding/decoding

- crates/primitives/src/aliases.rs
- crates/primitives/src/bits/address.rs
- crates/primitives/src/lib.rs
See added docs.
- add a deprecated `B160` at crate root which replaces the `aliases::B160` re-export
- keep `aliases::B160` as `doc(hidden)` (mentioned in `crate::B160` docs), in case someone really wants to use it
> chore(primitives): discourage use of `B160`

- crates/json-abi/src/abi.rs
- crates/json-abi/src/lib.rs
- crates/json-abi/src/to_sol.rs
- crates/sol-macro/src/json.rs
- crates/sol-type-parser/src/type_spec.rs
Rewrite code that generates Solidity tokens from a `JsonAbi` in `sol-macro` to use strings in `json-abi`.
- [no] Breaking changes
> feat: implement abi2sol

- crates/sol-macro/src/attr.rs
- crates/sol-macro/src/expand/contract.rs
- crates/sol-macro/src/expand/function.rs
- crates/sol-macro/src/expand/mod.rs
- crates/sol-macro/src/input.rs
- crates/sol-macro/src/json.rs
- crates/sol-macro/src/lib.rs
- crates/sol-types/tests/sol.rs
- crates/syn-solidity/src/type/function.rs
- crates/syn-solidity/src/variable/list.rs
Helps with compilation speed, most of the time these are not used. In the future it's possible to further expand these attributes to declare a list of item names to include, instead of adding it to either none or all items.
> feat(sol-macro): add opt-in attributes for extra methods and derives

- crates/sol-types/tests/ui/imports.rs
- crates/sol-types/tests/ui/imports.stderr
- crates/syn-solidity/src/item/import.rs
- crates/syn-solidity/src/lit/str.rs
- crates/syn-solidity/src/macros.rs
Some `Option`s were missing from `syn-solidity` imports. These were missed because all contract tests were flattened from the original repos which removes `import` statements.
> fix(syn-solidity): imports

- crates/primitives/src/bits/fixed.rs
- crates/primitives/src/bits/macros.rs
Sync `wrap_fixed_bytes!` macro with `FixedBytes` docs.
> docs: update fixed bytes docs

- crates/sol-macro/src/expand/mod.rs
- crates/syn-solidity/Cargo.toml
- crates/syn-solidity/src/attribute/function.rs
- crates/syn-solidity/src/item/function.rs
- crates/syn-solidity/src/type/mapping.rs
- crates/syn-solidity/src/type/mod.rs
- crates/syn-solidity/src/variable/mod.rs
Closes #253
Recurse into mappings in value positions, adding keys to the arguments list, and setting the last non-mapping value as the return value.
> feat(syn-solidity): improve variable getters generation

- crates/sol-macro/src/expand/error.rs
- crates/sol-macro/src/expand/function.rs
- crates/sol-macro/src/expand/mod.rs
- crates/sol-macro/src/expand/struct.rs
- crates/sol-types/Cargo.toml
- crates/sol-types/tests/sol.rs
When using a derive macro inside of the sol! macro, field attributes are not propagated to the expanded item.
Added 'attrs' parameter to 'expand_field'
Passed 'attrs' arg to 'expand_field' in 'expand_fields'
Moved 'pub' visibility specification to 'expand_field'
> feat(sol-macro): expand fields with attrs

- crates/sol-macro/src/expand/mod.rs
- crates/sol-macro/src/expand/ty.rs
- crates/sol-macro/src/expand/var_def.rs
- crates/sol-types/tests/sol.rs
- crates/sol-types/tests/ui/type.rs
- crates/sol-types/tests/ui/type.stderr
- crates/sol-types/tests/ui/var_def.rs
- crates/sol-types/tests/ui/var_def.stderr
- crates/syn-solidity/src/type/mod.rs
Follow up to (and based on) #260.
Expand stuff like:
```solidity
struct Data {
uint a;
uint[] b;
// this doesn't currently work when generating the struct, but it should be skipped
// in `getData` below regardless
mapping(uint => bool) map;
}
mapping(uint => Data) public getData;
```
to
```solidity
// skipped Data.b, Data.map from return value
function getData(uint) public view returns (uint);
```
> feat(sol-macro): expand getter functions' return types

- Cargo.toml
- crates/dyn-abi/Cargo.toml
- crates/json-abi/Cargo.toml
anstyle requires 1.70 as of 1.0.3.
> dep: pin anstyle to 1.65 compat

- crates/primitives/src/lib.rs
Document correct usage of `ruint::uint` macro
https://github.com/recmo/uint/issues/307
> doc: add note regarding ruint::uint macro

- crates/primitives/src/bits/fixed.rs
- crates/primitives/src/bytes/mod.rs
> feat(primitives): improve Bytes

- crates/dyn-abi/src/ty.rs
- crates/sol-types/src/coder/decoder.rs
- crates/sol-types/src/coder/encoder.rs
- crates/sol-types/src/eip712.rs
- crates/sol-types/src/lib.rs
- crates/sol-types/src/types/data_type.rs
- crates/sol-types/src/types/ty.rs
- crates/sol-types/tests/doctests/events.rs
- crates/sol-types/tests/doctests/types.rs
- crates/sol-types/tests/sol.rs
> feat: use `FixedBytes` for `sol_data::FixedBytes`

- crates/syn-solidity/src/item/function.rs
- crates/syn-solidity/tests/parse.rs
> fix(syn-solidity): parse modifiers without parens

- Cargo.toml
Don't know why this doesn't throw a warning or error
> fix: rand default-features typo

- crates/dyn-abi/README.md
- crates/dyn-abi/benches/abi.rs
- crates/dyn-abi/src/ext/abi.rs
- crates/dyn-abi/src/ty.rs
- crates/dyn-abi/src/value.rs
- crates/sol-types/src/coder/decoder.rs
- crates/sol-types/src/coder/encoder.rs
- crates/sol-types/src/coder/mod.rs
- crates/sol-types/src/coder/token.rs
- crates/sol-types/src/lib.rs
- crates/sol-types/src/types/enum.rs
- crates/sol-types/src/types/error.rs
- crates/sol-types/src/types/event/mod.rs
- crates/sol-types/src/types/function.rs
- crates/sol-types/src/types/ty.rs
- crates/sol-types/src/types/udt.rs
- crates/sol-types/tests/doctests/structs.rs
- crates/sol-types/tests/doctests/types.rs
- crates/sol-types/tests/sol.rs
More intuitive
- `{encode,decode}` -> `{encode,decode}_sequence`
- `{encode,decode}_single` -> `{encode,decode}`
> chore: rename coding functions

- .github/workflows/ci.yml
- crates/dyn-abi/benches/types.rs
- crates/dyn-abi/src/resolve.rs
- crates/dyn-abi/src/ty.rs
- crates/sol-type-parser/Cargo.toml
- crates/sol-type-parser/README.md
- crates/sol-type-parser/src/error.rs
- crates/sol-type-parser/src/ident.rs
- crates/sol-type-parser/src/lib.rs
- crates/sol-type-parser/src/root.rs
- crates/sol-type-parser/src/stem.rs
- crates/sol-type-parser/src/tuple.rs
- crates/sol-type-parser/src/type_spec.rs
Easier to expand in the future.
Performance is slightly better, but most of this is probably because of dropped white space support:
```clojure
parse/keywords          time:   [43.696 ns 43.795 ns 43.931 ns]                           
change: [-10.604% -10.130% -9.6426%] (p = 0.00 < 0.05)
Performance has improved.
parse/complex           time:   [1.3464 µs 1.3520 µs 1.3588 µs]                           
change: [-34.803% -34.511% -34.196%] (p = 0.00 < 0.05)
Performance has improved.
```
> refactor: rewrite type parser with `winnow`

- crates/dyn-abi/src/eip712/coerce.rs
- crates/dyn-abi/src/eip712/parser.rs
- crates/dyn-abi/src/eip712/resolver.rs
- crates/dyn-abi/src/resolve.rs
Minor thing for better error messages in case of failure
A lot of times this is not possible because error types do not implement Eq, or deref coersion can't happen when comparing results (e.g. `Result<String>` vs `Result<&str>`)
> chore: assert_eq! on Ok instead of unwrapping where possible

- crates/primitives/src/lib.rs
- crates/primitives/src/utils.rs
Ref https://github.com/paradigmxyz/reth/pull/4758
> hash_message

- crates/primitives/src/utils.rs
- crates/sol-macro/src/expand/contract.rs
- crates/sol-types/tests/sol.rs
Types are resolved, but they cannot be referenced in an inner module (contract) because of no `use super::*;`.
> fix: add super import on generated modules

- crates/sol-types/src/lib.rs
- crates/sol-types/src/types/error.rs
- crates/sol-types/src/types/mod.rs
Related to paradigmxyz/reth#4789
I moved `decode_revert_reason` function here and also add tests:
1. first test is for properly decoding a solidity revert reason
2. second one is properly decoding a random revert reason (should fit for vyper revert reasons)
3. last one to test that too short reason fail since `out.len() < Selector::len_bytes()`
Actually the last test makes me wonder if it is ok to put that `if` sentence in the first line of the function as it could happen that a vyper revert reason is actually shorter than 4 bytes but still valid.
Let me know WDYT.
Also, before I can delete this function from Reth, this PR needs to be merged. Otherwise in Reth there are errors because `decode_revert_reason` does not have any definition.
> test: move `decode_revert_reason` to alloy and add tests

- crates/sol-types/src/types/data_type.rs
> chore: simpler ENCODED_SIZE for SolType tuples

- crates/syn-solidity/src/macros.rs
- crates/syn-solidity/src/stmt/for.rs
- crates/syn-solidity/src/stmt/var_decl.rs
Added missing hooks for all statements and expressions types
See #236 
Implemented all the hooks inside the make_visitor macro
> feat(syn-solidity): visitor hooks for statements and expressions

- crates/sol-type-parser/Cargo.toml
For some reason prints don't get captured by libtest so running `test --all-features` floods your terminal
> chore: don't pass debug feature to winnow

- crates/sol-macro/Cargo.toml
- crates/sol-macro/src/attr.rs
- crates/sol-macro/src/expand/contract.rs
- crates/sol-macro/src/expand/error.rs
- crates/sol-macro/src/expand/event.rs
- crates/sol-macro/src/expand/function.rs
> feat(sol-macro): add docs to generated items

- crates/dyn-abi/src/lib.rs
Only has the one trait we export anyway
> chore(dyn-abi): make `resolve` module private

- crates/json-abi/src/item.rs
Based on #329
Simplifies serde for items and `AbiItem` by using `tag = "type"` on the item structs directly.
Perf is slightly (2-5%) better for ser, while unchanged for de
> refactor(json-abi): remove duplicate item serde hack

- crates/dyn-abi/Cargo.toml
- crates/dyn-abi/src/eip712/parser.rs
- crates/dyn-abi/src/eip712/resolver.rs
- crates/dyn-abi/src/resolve.rs
- crates/dyn-abi/src/token.rs
- crates/dyn-abi/src/ty.rs
- crates/dyn-abi/src/value.rs
- crates/json-abi/Cargo.toml
- crates/json-abi/src/abi.rs
- crates/json-abi/src/internal_type.rs
- crates/json-abi/src/item.rs
- crates/json-abi/src/lib.rs
- crates/json-abi/src/param.rs
- crates/json-abi/src/utils.rs
- crates/primitives/Cargo.toml
- crates/sol-type-parser/Cargo.toml
- crates/sol-type-parser/README.md
- crates/sol-type-parser/src/error.rs
- crates/sol-type-parser/src/lib.rs
- crates/sol-type-parser/src/parameter.rs
- crates/sol-type-parser/src/root.rs
- crates/sol-type-parser/src/stem.rs
- crates/sol-type-parser/src/tuple.rs
- crates/sol-type-parser/src/type_spec.rs
- crates/sol-types/src/abi/token.rs
Add `FromStr` and `parse` associated functions to `json-abi` items and params.
Supersedes #310
Closes #291
> feat: add parsing support for JSON items

- crates/sol-types/src/types/data_type.rs
- crates/sol-types/src/types/event/topic.rs
Encode `T`s into `U`s, not the opposite
> chore(sol-types): rewrite encodable impl generics

- crates/dyn-abi/src/eip712/typed_data.rs
Closes #334
Add rename to serde derive, and add a test for round-trip serialization
> fix: serde rename resolver to types

- crates/sol-macro/src/attr.rs
- crates/sol-macro/src/expand/contract.rs
- crates/syn-solidity/src/item/mod.rs
- crates/syn-solidity/src/variable/mod.rs
Previously we just appended the attributes once to the stream, but this ignored function return structs for example
> fix(sol-macro): pass attributes to all generated items

- crates/json-abi/src/to_sol.rs
Hey so was seeing what would happen if I ran all of the abis ever verified on etherscan through alloy's `sol` macro and this was one of the errors I ran into.
This error occurs due to the fact that when we go to convert parsed json-abi into a interface for syn-solidity to then parse as a normalization step, the anonymous keyword on events was not getting included into the interface and was causing an error.
Heres an example:
https://etherscan.io/address/0x29c1aaa2e5bd43692f516d9a0c3d2a0f37b59053#code
> fix: json-abi not using anonymous when converting to interface

- crates/sol-macro/Cargo.toml
- crates/sol-macro/src/expand/contract.rs
- crates/sol-macro/src/expand/mod.rs
- crates/sol-macro/src/expand/struct.rs
- crates/sol-macro/src/expand/ty.rs
- crates/sol-macro/src/lib.rs
- crates/sol-types/tests/sol.rs
- crates/sol-types/tests/ui/overloads.stderr
- crates/syn-solidity/src/ident/path.rs
- crates/syn-solidity/src/item/contract.rs
- crates/syn-solidity/src/item/function.rs
Use `proc-macro-error` to emit nicer diagnostics
> feat(sol-macro): improve error messages

- crates/json-abi/src/abi.rs
- crates/sol-macro/src/json.rs
Huff uses `runtime`; allow empty ABI
> feat(json-abi): deserialize more ContractObjects

- crates/sol-types/tests/sol.rs
- crates/syn-solidity/src/item/event.rs
- crates/syn-solidity/src/type/array.rs
Fixes #352
`TypeArray::is_abi_dynamic`
- if the array is not dynamic, return `Type::is_abi_dynamic`
- if the array is dynamic, return true
> fix(sol-macro): correct `TypeArray::is_abi_dynamic`

- crates/sol-types/src/types/value.rs
1. it's `target_pointer_width`, not `pointer_width`
2. it doesn't currently work with the generic ints since each bit size can only have one corresponding int type (64 -> i64 and that's it)
> chore(sol-types): remove impls for isize/usize

- .github/workflows/ci.yml
`check` mode does not catch all errors since it does not codegen.
> ci: cargo build instead of check

- Cargo.toml
- crates/dyn-abi/Cargo.toml
- crates/dyn-abi/benches/abi.rs
- crates/dyn-abi/src/arbitrary.rs
- crates/dyn-abi/src/coerce.rs
- crates/dyn-abi/src/eip712/coerce.rs
- crates/dyn-abi/src/eip712/typed_data.rs
- crates/dyn-abi/src/error.rs
- crates/dyn-abi/src/lib.rs
- crates/dyn-abi/src/ty.rs
- crates/dyn-abi/src/value.rs
- crates/json-abi/src/item.rs
- crates/json-abi/src/utils.rs
- crates/primitives/src/bits/address.rs
- crates/primitives/src/signed/int.rs
- crates/sol-type-parser/Cargo.toml
- crates/sol-type-parser/src/error.rs
- crates/sol-type-parser/src/ident.rs
- crates/sol-type-parser/src/lib.rs
- crates/sol-type-parser/src/parameter.rs
- crates/sol-type-parser/src/root.rs
- crates/sol-type-parser/src/stem.rs
- crates/sol-type-parser/src/tuple.rs
- crates/sol-type-parser/src/type_spec.rs
- crates/sol-type-parser/src/utils.rs
- crates/sol-types/src/types/ty.rs
Port of [`ethabi::Tokenizer`](https://docs.rs/ethabi/latest/ethabi/token/trait.Tokenizer.html), with extra features
> feat(dyn-abi): `DynSolType::coerce_str`

- crates/sol-types/src/types/error.rs
- crates/sol-types/src/types/interface.rs
> fix(sol-types): `SolInterface::MIN_DATA_LENGTH` overflow

- crates/dyn-abi/src/arbitrary.rs
Previously we generated integers and fixed bytes separate from eachother, which has a very high chance of generating "invalid" values
cc @Evalir
> fix(dyn-abi): generate Int, Uint, FixedBytes adjusted to their size

- Cargo.toml
- crates/primitives/src/signed/conversions.rs
- crates/primitives/src/signed/errors.rs
- crates/primitives/src/signed/int.rs
- crates/primitives/src/signed/ops.rs
- crates/primitives/src/signed/utils.rs
> fix(primitives): Signed cleanup

- crates/json-abi/src/utils.rs
- crates/sol-type-parser/src/root.rs
- crates/sol-type-parser/src/type_spec.rs
Fixes https://github.com/foundry-rs/foundry/issues/6195
> fix(sol-type-parser): normalize `u?int` to `u?int256`

- Cargo.toml
- crates/sol-type-parser/src/utils.rs
- crates/sol-types/src/abi/encoder.rs
`separated0` and `separated1` are now deprecated.
> chore: use winnow `separated` instead of `separated0`

- crates/sol-types/src/abi/decoder.rs
Utility methods I found I needed when using outside of the crate
> feat(sol-types): add some more methods to `abi::Decoder`

- crates/dyn-abi/src/ty.rs
I saw the open issue #402 and decided to implement it
Simply added hash to the structs and tests to make sure nothing broke
- [] Added Tests - No, it's a default crate feature
- [?] Added Documentation - Not sure if there was a need
- [] Breaking changes - No
> feat: Added Hash to DynSolType and StructProp

- crates/sol-macro/src/expand/struct.rs
- crates/sol-macro/src/expand/udt.rs
- crates/sol-types/src/types/data_type.rs
- crates/sol-types/src/types/ty.rs
- crates/sol-types/src/types/udt.rs
- crates/syn-solidity/src/type/mod.rs
`SolType::ENCODED_SIZE` for UDVTs and custom structs were incorrect because they were not specified and would use the confusing default of `Some(32)`.
> fix(sol-types): remove `SolType::ENCODED_SIZE` default

- crates/dyn-abi/src/arbitrary.rs
- crates/dyn-abi/src/coerce.rs
- crates/dyn-abi/src/eip712/parser.rs
- crates/dyn-abi/src/eip712/resolver.rs
- crates/dyn-abi/src/eip712/typed_data.rs
- crates/dyn-abi/src/error.rs
- crates/dyn-abi/src/lib.rs
- crates/dyn-abi/src/resolve.rs
- crates/dyn-abi/src/ty.rs
- crates/json-abi/src/abi.rs
- crates/json-abi/src/internal_type.rs
- crates/json-abi/src/item.rs
- crates/json-abi/src/lib.rs
- crates/json-abi/src/param.rs
- crates/json-abi/src/utils.rs
- crates/sol-type-parser/src/utils.rs
Ref https://github.com/alloy-rs/core/issues/389
> feat(json-abi): permit keyword prefixes in HR parser

- Cargo.toml
- crates/primitives/Cargo.toml
Enables ruint ssz feature when alloy-primitives SSZ feature is enabled
Blocked by release of ruint@1.11.1 https://github.com/recmo/uint/pull/345
> feat: enable ruint ssz when primitives ssz

- crates/sol-macro/src/expand/to_abi.rs
- crates/sol-types/tests/macros/sol/abi.rs
Follow-up fix to #422
Previously custom type in parameters would get formatted as "tuple" even when not tuples, like enums.
> fix(sol-macro): correctly print Custom types in parameters

- crates/primitives/src/log.rs
- crates/sol-macro/src/expand/contract.rs
- crates/sol-macro/src/verbatim.rs
- crates/sol-types/Cargo.toml
- crates/sol-types/src/abi/token.rs
- crates/sol-types/src/errors.rs
- crates/sol-types/src/lib.rs
- crates/sol-types/src/types/event/mod.rs
- crates/sol-types/src/types/event/topic_list.rs
- crates/sol-types/src/types/interface/event.rs
- crates/sol-types/src/types/interface/mod.rs
- crates/sol-types/src/types/mod.rs
- crates/sol-types/tests/macros/sol/mod.rs
> feat(sol-macro): `SolEventInterface`: `SolInterface` for contract events enum

- crates/sol-types/src/types/interface/mod.rs
> fix(sol-types): ContractError decoding

- crates/sol-types/src/abi/mod.rs
- crates/sol-types/src/types/value.rs
Avoids going through the entire encoding when doing `"".abi_encode()`
> feat(sol-types): add empty `bytes` and `string` specialization

- crates/primitives/src/bits/fixed.rs
- crates/primitives/src/bits/macros.rs
Current `try_from` and `from_slice` requires exact length. These convenience functions provide variants that support shorter slices by left- or right-padding to the correct length
> feat(primitives): left and right padding conversions

- crates/dyn-abi/src/coerce.rs
- crates/primitives/src/bytes/mod.rs
- crates/primitives/src/bytes/serde.rs
- crates/sol-types/src/types/data_type.rs
Don't print "Bytes()" in Debug
> feat(primitives): update Bytes formatting, add UpperHex

- crates/primitives/src/bits/ssz.rs
Fixes https://github.com/alloy-rs/core/issues/448
Fixed length objects should return the number of bytes this object occupies in the fixed-length portion of the SSZ bytes. Without an implementation it defaults to `BYTES_PER_LENGTH_OFFSET` which is wrong for fixed size.
Add trait method implementation that returns correct length.
> fix(primitives): return correct fixed length in ssz::Encode

- crates/sol-types/src/lib.rs
- crates/sol-types/src/types/error.rs
- crates/sol-types/src/types/interface/mod.rs
- crates/sol-types/src/types/mod.rs
Adding the `RevertReason` enum addresses the need to encapsulate and distinguish reasons for reverts.
Should close #449.
Introducing the `RevertReason` enum offers a structured way to represent both detailed contract errors and raw string messages as reasons for reverts, enhancing clarity and flexibility in error handling within the codebase.
> feat: add `RevertReason` enum

- crates/primitives/src/bits/address.rs
Convenience method to instantiate an address from pubkey bytes
> feature: address from pubkey

- crates/dyn-abi/src/lib.rs
- crates/dyn-abi/src/ty.rs
Closes #392 
Fix here prevents zero-sized types from adding significant overhead to decoding, this is an alternative to the proposed fix of disabling instantiation of ZSTs. `DynSolType` has many instantiation vectors, and we may not be able to effectively prevent incorrect use of all of them. 
Followup: research whether we can do this effectively
Add an `is_zst` check to decoding, which short-circuits decoding of zero-sized values.
> fix: don't decode ZSTs

- crates/dyn-abi/src/eip712/parser.rs
- crates/dyn-abi/src/eip712/resolver.rs
- crates/dyn-abi/src/eip712/typed_data.rs
Closes #452 
Properly ingest the domain into the type resolver when instantiating a typed data from a struct
Fix parser to allow empty types
> fix: ingest domain when instantiating TypedData

- Cargo.toml
- crates/primitives/Cargo.toml
- crates/primitives/src/lib.rs
- crates/primitives/src/postgres.rs
- crates/primitives/src/signed/int.rs
- crates/sol-macro/src/lib.rs
Changes made as requested according to this issue https://github.com/alloy-rs/core/issues/365
Closes #365
Applying toSql and FromSql traits from Postgres_types package to FixedBytes and Signed Type.
> Add ToSql and FromSql to Signed and FixedBytes

- crates/primitives/src/lib.rs
- crates/primitives/src/sealed.rs
Moves `Sealed` and `Sealable` into alloy-primitives
Commonly used across many potential networks and crates.
Make `Sealed` and `Sealable` primitives
> feature: sealed

- crates/dyn-abi/src/event.rs
- crates/dyn-abi/src/ext/event.rs
- crates/primitives/src/bits/bloom.rs
- crates/primitives/src/lib.rs
- crates/primitives/src/log.rs
- crates/sol-macro/src/expand/contract.rs
- crates/sol-types/src/errors.rs
- crates/sol-types/src/lib.rs
- crates/sol-types/src/types/event/mod.rs
- crates/sol-types/src/types/interface/event.rs
CC @Evalir  @DaniPopes 
Refactors log to support address and raw/decoded data 
- rename `Log` to `LogData`
- make `Log<T = LogData>`
- modify `SolEvent` and `SolEventInterface` to decode into `Log<Self>`
- rename functions for added clarity
- implement RLP on `Log` (needs testing)
- expand `Bloom` with `FromIterator` and `Extend`, and specialized `contains` methods for logs
> refactor: Log implementation

- crates/primitives/src/sealed.rs
I need to let Dani review before merging 
I need to let Dani review before merging 
I need to let Dani review before merging 
I need to let Dani review before merging 
Expand docs and move attrs below
> fix: clean the sealed

- crates/primitives/src/bits/address.rs
- crates/primitives/src/lib.rs
- crates/primitives/src/utils/mod.rs
- crates/sol-types/src/eip712.rs
- crates/sol-types/src/types/struct.rs
Now that we have multiple Keccak-256 back-ends which support an update-finalize API, we should expose this publicly.
> feat(primitives): add Keccak256 hasher struct

- crates/sol-type-parser/src/type_spec.rs
> feat(sol-type-parser): improve error message for bad array size

- crates/primitives/Cargo.toml
- crates/primitives/src/bits/address.rs
- crates/primitives/src/lib.rs
- crates/primitives/src/signature.rs
- crates/primitives/src/signature/error.rs
- crates/primitives/src/signature/mod.rs
- crates/primitives/src/signature/parity.rs
- crates/primitives/src/signature/sig.rs
- crates/primitives/src/signature/utils.rs
Add a primitive `Signature` type to support ongoing work in alloy transaction models
- Add `Signature` to primitives crate
- Add `k256` feature
- Add `Address::from_public_key` convenience function
> feat(primitives): add Signature type and utils

- crates/primitives/src/signature/parity.rs
I don't believe ignoring `Parity` (0, 1) is valid here since we get this variant when instantiating the `k256` signature.
Encountered in https://github.com/alloy-rs/alloy/pull/83 when applying the signer's EIP-155 chain ID after signing, which was a no-op before this PR.
> fix(primitives): also apply EIP-155 to Parity::Parity

- crates/json-abi/src/item.rs
- crates/json-abi/src/param.rs
- crates/json-abi/src/utils.rs
I’m working on a ABI fragments database so we can fill in function and event data for contracts that haven’t been verified, but we having a matching ABI fragment for from another contract.
We’re going to have each row be unique based on the `full_signature`, which includes the name of each param, for events, whether the param is indexed or not, and for functions, the state mutability
In `ethers.js`, there is a fragment `FormatTypes.full` that can generate the full signature for you.
https://docs.ethers.org/v5/api/utils/abi/fragments/#fragments--output-formats
some maximally illustrative examples:
`function batchSwapExactIn(tuple(address pool, uint256 tokenInParam, uint256 tokenOutParam, uint256 maxPrice)[] swaps, address tokenIn, address tokenOut, uint256 totalAmountIn, uint256 …
> feat(json-abi): add full_signature

- crates/primitives/src/bits/address.rs
- crates/primitives/src/bits/fixed.rs
- crates/sol-types/tests/ui/keywords.stderr
> feat(primitives): add `Address::from_private_key`

- crates/json-abi/src/abi.rs
- crates/json-abi/tests/abi.rs
- crates/json-abi/tests/testdata/UnlinkedNouns.json
ref https://github.com/foundry-rs/foundry/issues/6815
improve error diagnostic for unlinked bytecodes
> chore: improve unlinked bytecode deserde error

- crates/sol-macro/src/input.rs
- crates/sol-types/tests/ui/features/json/abigen.stderr
- crates/sol-types/tests/ui/features/not(json)/abigen.stderr
the io::Error does not contain the file path.
this includes the file path in errors
> chore: include path in error

- crates/json-abi/src/to_sol.rs
- crates/json-abi/tests/abi/AggregationRouterV5.sol
- crates/json-abi/tests/abi/BlurExchange.sol
- crates/json-abi/tests/abi/DoubleExponentInterestSetter.sol
- crates/json-abi/tests/abi/GaugeController.sol
- crates/json-abi/tests/abi/GnosisSafe.sol
- crates/json-abi/tests/abi/Junkyard.sol
- crates/json-abi/tests/abi/LiquidityGaugeV4.sol
- crates/json-abi/tests/abi/Seaport.sol
- crates/json-abi/tests/abi/UniswapV2Factory.sol
- crates/json-abi/tests/abi/UniswapV2FactoryWithMigrator.sol
- crates/json-abi/tests/abi/ZRXToken.sol
- crates/json-abi/tests/abi/ZeroXExchange.sol
- crates/sol-macro/src/expand/function.rs
- crates/sol-types/src/lib.rs
- crates/sol-types/src/types/function.rs
- crates/sol-types/src/types/mod.rs
- crates/sol-types/tests/doctests/contracts.rs
- crates/sol-types/tests/macros/sol/json.rs
I needed to encode constructor args to create a contract creation tx, and saw #482.
* Adding `SolConstructor` trait 
* Handle constructor in `function::expand()` (creating a constructorCall struct  that impl `SolConstructor`)
* impl `ToSol` for `Constructor`
* Adding `AbiFunctionKw::Constructor` variant
* Update fixtures in "tests/abi"
> feat: add constructorCall to `sol!`

- crates/primitives/src/signature/parity.rs
In the case of a signature without EIP155 applied, the `y_parity` byte should be returned as 27 or 28. `y_parity_byte` only returns it as `{0,1}`.
This adds a fn `y_parity_byte_non_eip155` which, when not having an EIP155 parity, we get 27 or 28, or `None` otherwise.
> feat(`primitives`): Add `y_parity_byte_non_eip155` to `Parity`

- crates/primitives/src/signature/sig.rs
Followup for #499.
In the cases when we do not have an EIP155 v, construct the signature using `y_parity_byte_non_eip155`, to add `27` to v if necessary.
> fix(`signature`): construct Signature bytes using v+27 when we do not have an EIP155 `v`

- crates/sol-macro/src/expand/contract.rs
- crates/sol-macro/src/utils.rs
Faster and maybe less binary size
> perf(sol-macro): use a lookup table when generating `SolInterface::abi_decode_raw`

- crates/primitives/src/signature/parity.rs
- crates/primitives/src/signature/sig.rs
The current way the serialization/deserialization of `Signature` is implemented only works for human readable (JSON) formats. However, binary formats like `bincode` that do not support `Deserializer::deserialize_identifier` are not supported.
Similar to #221, this PR uses the `is_human_readable()` flag to distinguish between using the current serialization (`SerializeMap`) or a `bincode` compatible version.
For this, the serialization is implemented as a tuple `(r: U256, s: U256, v: u64)`.
> fix: Signature bincode serialization

- README.md
Since the main README.md file from the root of the repository is used in the `crates/core` dir as well, the relative paths were not working. You can try to access any of the relative paths in the `overview` section of the README.md file in `crates/core` of the main repository here: https://github.com/alloy-rs/core/tree/main/crates/core
As you notice, none of them work.
I merely changed the relative paths so that they all start at the root.
> docs: fix relative paths in README files

- crates/dyn-abi/src/eip712/coerce.rs
In the course of [implementing dynamic EIP-712 typed data signing](https://github.com/alloy-rs/alloy/issues/202) on the alloy repo, I encountered an issue ([see this comment](https://github.com/alloy-rs/alloy/issues/202#issuecomment-1961983276))  where `bytes` are being encoded as an array of numbers by `TypedData::from_struct`, causing  an error when `eip712_signing_hash()` is called on the returned value: `TypeMismatch { expected: "bytes", actual: "[102,105,122,122]" }
`.
@prestwich suggested the code ([see comment](https://github.com/alloy-rs/alloy/issues/202#issuecomment-1965141653)) that is contained in this PR in order to resolve the issue.
add logic to the `bytes()` function used in `DynSolType.coerce_json_simple()` to handle case where the `input` value is an array of numbers …
> fix(dyn-abi): enable `DynSolType.coerce_json` to convert array of numbers to bytes

- crates/core/src/lib.rs
- crates/primitives/src/lib.rs
And removes the doc override added in https://github.com/alloy-rs/core/pull/265 thanks to https://github.com/recmo/uint/pull/351 (blocked on a new release first).
> feat(core): re-export `uint!`

- crates/dyn-abi/src/eip712/coerce.rs
- crates/dyn-abi/src/eip712/typed_data.rs
- crates/primitives/src/common.rs
- crates/primitives/src/lib.rs
- crates/sol-types/src/lib.rs
- crates/sol-types/tests/macros/main.rs
This type started causing a circular dependency in https://github.com/alloy-rs/alloy/pull/190, so I opted to move it to the primitives crate
> feat: add `TxKind`

- crates/dyn-abi/src/coerce.rs
- crates/json-abi/src/utils.rs
- crates/primitives/src/bits/fixed.rs
- crates/primitives/src/bits/macros.rs
- crates/sol-type-parser/src/parameter.rs
- crates/sol-type-parser/src/utils.rs
- crates/sol-types/src/abi/encoder.rs
- crates/sol-types/tests/ui/keywords.stderr
- scripts/bless_tests.sh
Two bugs in here:
- the element parser was getting called on an empty list like "[]" with "]", which should be special cased to just return the empty list without calling the element parser IMO
- an empty string was getting incorrectly parsed as an empty byte hex string like "0x", but we shouldn't allow this
Fixes https://github.com/foundry-rs/foundry/issues/7280
> fix(dyn-abi): correctly parse empty lists of bytes

- crates/dyn-abi/benches/types.rs
- crates/dyn-abi/src/eip712/resolver.rs
- crates/dyn-abi/src/ext/abi.rs
- crates/dyn-abi/src/ext/event.rs
- crates/dyn-abi/src/lib.rs
- crates/dyn-abi/src/resolve.rs
- crates/dyn-abi/src/ty.rs
Prep for more `DynSol____` by unifying resolution under the concept of a `Specifier<T>`. A specifier is any data that specifies a Solidity interface item. E.g. the string `"bytes memory"`,  the solidity code `function a()` or a JSON ABI object.
This PR preps for adding `DynSolFunc` and `DynSolError` and removal or modification of `JsonAbiExt` and related traits in favor of shortcut encoding traits blanket implemented on `Specifier<T>` 
Unify `ResolveSolType` and `ResolveSolEvent` into `Specifier<T>`
> refactor: change identical resolve traits to Specifier<T>

- crates/dyn-abi/src/coerce.rs
- crates/sol-macro/src/attr.rs
- crates/sol-macro/src/expand/contract.rs
- crates/sol-types/tests/macros/sol/mod.rs
Const-eval is not very fast at doing stuff in general
> perf(sol-macro): decode bytecode hex strings ourselves

- crates/sol-macro/src/expand/contract.rs
- crates/sol-macro/src/lib.rs
Companion to https://github.com/alloy-rs/alloy/pull/274
Example usage: https://github.com/alloy-rs/alloy/blob/14a797b42cbfbdc857f0b0265e7c562df63d7f98/crates/contract/src/event.rs#L165
> feat(sol-macro): add event filters to contracts

- crates/primitives/src/log.rs
- crates/sol-macro/src/expand/event.rs
- crates/sol-types/Cargo.toml
- crates/sol-types/src/abi/token.rs
- crates/sol-types/tests/doctests/events.rs
closes #544
Allow rlp encoding of logs after their data has been ABI decoded.
Add a set of methods and a blanket Encode implementation for 
`Log<T> where for<'a> &'a T: Into<LogData>,`
Note that this change does not allow decoding, as that would require embedding the ABI error into the RLP error decode impl
> feat: rlp encoding for logs with generic event data

- CONTRIBUTING.md
- crates/primitives/src/postgres.rs
- crates/syn-solidity/tests/contracts/PrbMath.sol
A common RPGF farming strategy is to open PRs to fix grammar/typos with a bot
Don't allow it
> docs: do not accept grammar prs

- .github/workflows/ci.yml
- crates/dyn-abi/benches/abi.rs
- crates/dyn-abi/benches/types.rs
- crates/json-abi/benches/json_abi.rs
- crates/primitives/benches/primitives.rs
Prevent future random CI breakage
closes #566 
Set clippy to stable in CI
there may be a better way to achieve this, but this way is straightforward
> fix: force clippy to stable

- crates/dyn-abi/src/coerce.rs
When using `coerce_str` to parse a uint from a decimal number in non-wei units, precision is lost due to use of `f64`. For example, parsing `123456.123456789123456789 ether` returns `123456123456789126578176` wei, but the correct value is `123456123456789123456789` wei.
I removed uses of `f64`, and all math is now done using `U256` only. This also means `std` is no longer required when parsing decimal numbers with `coerce_str`.
I also added test cases that fail without this change.
> fix(dyn-abi): correctly parse uints in `coerce_str`

- crates/sol-macro/src/expand/contract.rs
- crates/sol-macro/src/lib.rs
To default Network parameters to Ethereum in `alloy-provider` and `alloy-contract`, they need to be moved to the last of the type params: https://github.com/alloy-rs/alloy/pull/356
According to those changes, we need to adjust the type param order in `sol!` as well.
from: https://github.com/alloy-rs/alloy/issues/263
> Rearranged type param order so that the Network param is the last

- crates/sol-macro/src/expand/event.rs
Fixes https://github.com/alloy-rs/alloy/issues/659, allowing for SolEvent to be cloned
> Add derive[Clone] to SolEvent creation

- crates/sol-macro/src/expand/event.rs
See https://github.com/alloy-rs/core/issues/588#issuecomment-2094823588
We want this `sol!` invocation to not generate a `missing_docs` warning:
```rust
sol! {
/// Emitted when `value` tokens are moved from one account (`from`) to
/// another (`to`).
///
/// Note that `value` may be zero.
event Transfer(address indexed from, address indexed to, uint256 value);
/// Emitted when the allowance of a `spender` for an `owner` is set by a
/// call to `approve`. `value` is the new allowance.
event Approval(address indexed owner, address indexed spender, uint256 value);
}
```
We add an `#[allow(missing_docs)]` annotation to the generated event struct fields. The alternative would be supporting:
```rust
sol! {
/// ...
event Approval(
/// ...
address indexed owner,
/// ...
address indexed spender, …
```
> feat(sol-macro): allow missing docs for event fields

- crates/dyn-abi/src/eip712/resolver.rs
- crates/dyn-abi/src/eip712/typed_data.rs
`TypeData` in `ethers_core` [derives](https://github.com/gakonst/ethers-rs/blob/51fe937f6515689b17a3a83b74a05984ad3a7f11/ethers-core/src/types/transaction/eip712.rs#L270) `PartialEq` and `Eq`, but it isn't derived in `alloy-dyn-abi`.
Derive `PartialEq` and `Eq` for `TypeData` in `alloy-dyn-abi`.
> feat(dyn-abi): derive `Eq` for `TypedData`

- crates/dyn-abi/Cargo.toml
- crates/sol-types/tests/compiletest.rs
`winnow/std` is now enabled by `toml`, which was added in the latest `trybuild` version. This breaks an internal hack in `winnow` regarding `std::error::Error`, so we have to enable `std` on ourselves too.
> chore: fix tests

- Cargo.toml
- crates/core/Cargo.toml
- crates/core/src/lib.rs
- crates/dyn-abi/Cargo.toml
- crates/sol-macro-expander/Cargo.toml
- crates/sol-macro-input/src/lib.rs
- crates/sol-macro/Cargo.toml
closes https://github.com/alloy-rs/core/issues/628
> fix(sol-macro): json feature

- crates/primitives/src/signature/parity.rs
As mentioned in #630 , there is a corner case for inverting parity with value of Eip155(0). Program will try to return Eip155(-1) which is panic issue. 
One should handle the 0 case separately and return Eip155(1) as the inverted output.
> fix: handle 0 for inverting eip155 parity.

- crates/json-abi/src/param.rs
- crates/sol-type-parser/src/error.rs
Resolve https://github.com/alloy-rs/core/issues/240
* Create a `new` method for `Param` and `EventParam` 
* Annotate the `ty` and `name` fields on `Param` and `EventParam` with `#[doc(hidden)]` to discourage users from creating their own isntances of those types wihtout using the `new` method. The reason for not making those fields private is that they are used by macros in different crates.
> feat: Create new method on Param and EventParam

- Cargo.toml
- crates/primitives/Cargo.toml
- crates/primitives/src/lib.rs
- crates/primitives/src/log.rs
- crates/primitives/src/log_serde.rs
Log flattens data for serde, which is an issue for a non self describing protocols as bcs and bincode. Without this fix test will fail with:
1. bcs:
```
---- log::tests::test_bcs_encode_decode stdout ----
thread 'log::tests::test_bcs_encode_decode' panicked at crates/primitives/src/log.rs:248:51:
called `Result::unwrap()` on an `Err` value: NotSupported("deserialize_any")
```
2. bincode:
```
---- log::tests::test_bincode_encode_decode stdout ----
thread 'log::tests::test_bincode_encode_decode' panicked at crates/primitives/src/log.rs:227:52:
called `Result::unwrap()` on an `Err` value: SequenceMustHaveLength
```
Code affected: reth_primitives::Receipt.
> Fix Log serde for non self describing protocols

- Cargo.toml
- crates/primitives/src/signed/int.rs
`sign_plus` flag (`{:+}`) would get printed twice as now `Uint` also formats it. Only this flag is affected which is pretty rare.
> fix(primitives): Signed formatting

- crates/sol-macro-expander/Cargo.toml
- crates/sol-macro-expander/src/expand/event.rs
- crates/sol-macro-expander/src/expand/mod.rs
- crates/sol-types/tests/macros/sol/mod.rs
The overridden name was used for calculating the signature, which is wrong.
Fixes https://github.com/alloy-rs/core/issues/640
> fix(sol-macro): overridden event signatures

- crates/sol-macro-expander/src/expand/contract.rs
- crates/sol-macro-input/src/attr.rs
- crates/sol-macro-input/src/lib.rs
- crates/sol-types/tests/macros/sol/mod.rs
Fixes https://github.com/alloy-rs/core/issues/618.
> fix(sol-macro): allow deriving `Default` on contracts

- crates/sol-types/tests/macros/sol/mod.rs
- crates/syn-solidity/src/item/function.rs
Example:
```rust
sol! {
contract Counter {
uint256 public number;
}
}
// Before:
Counter::numberReturn { _0: U256 }
// After:
Counter::numberReturn { number: U256 }
```
See the added test
> feat(sol-macro): add return value names to simple getters

- crates/primitives/src/signature/parity.rs
- crates/primitives/src/signature/sig.rs
Needed for https://github.com/alloy-rs/alloy/issues/109. 
primitive `Signature` and `Parity` types do not derive `Arbitrary`. But the `Transaction` type in alloy requires it. 
Derive `Arbitrary` for the test and arbitrary feature.
> feat(primitives): derive `Arbitrary` for Signature

- crates/primitives/src/aliases.rs
Closes: https://github.com/alloy-rs/core/issues/653
For context + related PR in `alloy`: https://github.com/alloy-rs/alloy/pull/859
Add generic aliases unrelated to specific EIPs
- `TxNonce` (with doc alias)
- `BlockTimestamp`
> feat(primitives): add additional common aliases

- crates/primitives/src/lib.rs
My apologies for the oversight. Low priority, can simply be part of a next release.
Export the new aliases: `TxNonce` and `BlockTimestamp` so they do not have to be imported as `aliases::{TxNonce, BlockTimestamp}`.
> fix(primitives): include in aliases export to prevent having to import from `aliases::{..}`

- crates/json-abi/src/item.rs
- crates/primitives/src/signature/parity.rs
- crates/primitives/src/signature/sig.rs
- crates/primitives/src/signed/int.rs
The underlying type doesn't need to implement the trait for `Signature` to do so
> feat(primitives): manually implement arbitrary for signature

- crates/dyn-abi/src/dynamic/event.rs
- crates/dyn-abi/src/dynamic/value.rs
- crates/dyn-abi/src/eip712/resolver.rs
- crates/primitives/src/log.rs
- crates/sol-macro-expander/src/expand/enum.rs
- crates/sol-macro-expander/src/expand/struct.rs
- crates/sol-macro-expander/src/expand/udt.rs
- crates/sol-types/src/lib.rs
- crates/sol-types/src/types/data_type.rs
- crates/sol-types/src/types/event/topic.rs
- crates/sol-types/src/types/ty.rs
For reserving before encoding in packed mode, and for calculating the padding needed at runtime for arrays
> feat: add `abi_packed_encoded_size`

- crates/dyn-abi/src/dynamic/event.rs
- crates/primitives/src/lib.rs
- crates/primitives/src/log.rs
- crates/sol-macro-expander/src/expand/contract.rs
- crates/sol-macro-expander/src/expand/event.rs
- crates/sol-types/src/lib.rs
- crates/sol-types/src/types/event/mod.rs
Groundwork for https://github.com/alloy-rs/alloy/issues/623
Adding this conversion trait allows us to bound receipt log vectors in more meaningful ways
Introduce trait for types which can be infallibly converted into LogData
> feat: IntoLogData

- crates/dyn-abi/src/dynamic/call.rs
- crates/dyn-abi/src/dynamic/mod.rs
- crates/dyn-abi/src/eip712/mod.rs
- crates/dyn-abi/src/ext/abi.rs
- crates/dyn-abi/src/lib.rs
- crates/dyn-abi/src/specifier.rs
Continue fleshing out dyn-abi to reach feature parity with sol-types
- Add `DynSolCall`
- Add `DynSolReturns`
- Add `impl Specifier<DynSolCall> for Function`
> feature: DynSolCall

- crates/sol-macro-expander/src/expand/contract.rs
```
warning: octal-looking escape in byte string literal
--> crates/contract/src/event.rs:207:31
|
207 | ... = "60808060405234601557610147908161001a8239f35b5f80fdfe6080806040526004361015610012575f80fd5b5f3560e01c908163299d8665146100a7575063ffdf4f1b14610032575f80fd5b346100a3575f3660031901126100a357602a7f6d10b8446ff0ac11bb95d154e7b10a73042fb9fc3bca0c92de5397b2fe78496c6040518061009e819060608252600560608301526468656c6c6f60d81b608083015263deadbeef604060a0840193600160208201520152565b0390a2005b5f80fd5b346100a3575f3660031901126100a3577f4e4cd44610926680098f1b54e2bdd1fb952659144c471173bbb9cf966af3a988818061009e602a949060608252600560608301526468656c6c6f60d81b608083015263deadbeef604060a084019360016020820152015256fea26469706673582212202e640cd14a7310d4165f902d2721ef5b4640a08f5ae38e9ae5c315a9f9f443586473 …
```
> chore(sol-macro): allow clippy all when emitting contract bytecode

- crates/core/Cargo.toml
- crates/core/src/lib.rs
- crates/primitives/Cargo.toml
- crates/primitives/src/lib.rs
- crates/primitives/src/signature/mod.rs
- crates/primitives/src/signature/sig.rs
Rustdoc operates in mysterious ways
Closes https://github.com/alloy-rs/core/issues/605
> docs(primitives): fix rustdoc for Signature

- crates/json-abi/Cargo.toml
- crates/json-abi/src/item.rs
- crates/json-abi/src/lib.rs
- crates/json-abi/src/utils.rs
- crates/sol-type-parser/Cargo.toml
- crates/sol-type-parser/src/lib.rs
- crates/sol-type-parser/src/state_mutability.rs
- crates/sol-type-parser/src/utils.rs
Closes #681
Closes https://github.com/alloy-rs/core/issues/389
> feat: add support for parsing visibility and state mutability

- crates/json-abi/src/to_sol.rs
- crates/sol-macro-expander/src/expand/contract.rs
- crates/sol-macro-expander/src/expand/mod.rs
- crates/sol-types/tests/macros/sol/json.rs
- crates/sol-types/tests/macros/sol/mod.rs
Makes `sol!` macro respect namespaces.
- `current_namespace` context variable is added to `ExpCtxt` which is switched when we enter/exit contract body during AST traversal or expansion.
- `all_items`, `custom_types` and `overloaded_items` are wrapped into `NamespacedMap` which resolves full `SolPath`s depending on current namespace
cc @DaniPopes please take a look and lmk if I should switch base to master instead
> feat: implement namespaces on `sol!` side

- crates/primitives/src/signed/int.rs
did not find a testcase for method: overflowing_from_sign_and_abs, so I added one
add testcase
> Add testcase for overflowing_from_sign_and_abs

- crates/primitives/src/signed/int.rs
- crates/primitives/src/signed/utils.rs
the underline ruint crate already have mask method
DRY
use ruint::mask
Fix #695
> chore(primitives): re-use ruint mask function

- crates/primitives/src/sealed.rs
> feat: derive `Hash` for `Sealed`

- crates/primitives/src/sealed.rs
Derive serde's `Serialize` and `Deserialize` on `Sealed`.
> feat: derive ser deser on `Sealed`

- Cargo.toml
- crates/sol-macro-expander/Cargo.toml
- crates/sol-macro-expander/src/expand/mod.rs
- crates/sol-macro-expander/src/expand/struct.rs
- crates/sol-macro-expander/src/expand/ty.rs
- crates/sol-macro/Cargo.toml
- crates/sol-macro/src/lib.rs
new advisory https://rustsec.org/advisories/RUSTSEC-2024-0370
> chore: use proc-macro-error2

- crates/core/src/lib.rs
- crates/primitives/src/lib.rs
- crates/primitives/src/signature/mod.rs
- crates/primitives/src/signature/sig.rs
Currently it is impossible to construct an invalid signature, because `k256` feature requires it to contain a valid `k256::Signature`. This makes it impossible to decode and store invalid signatures. 
For example, we require this in reth to keep deposit transaction signatures: https://github.com/paradigmxyz/reth/blob/42dc5eea1685385b835edd03029640609f4c4ab4/crates/primitives/src/transaction/signature.rs#L200
Remove generic from `Signature`. Instead, we now convert signature into `k256::Signature` during recovery.
> refactor: remove `Signature` generic

- crates/sol-macro-expander/src/expand/mod.rs
- crates/sol-types/tests/macros/sol/mod.rs
Currently type resolution does not handle namespaces correctly, causing such example to fail:
```rust
alloy_sol_types::sol! {
library LibA {
struct B {
uint256 val;
}
struct A {
B val;
}
}
library LibB {
struct Nested {
uint256 val1;
LibA.A val2;
}
}
contract A {
function get_val(LibB.Nested memory user) external;
}
}
```
When resolving `LibB.Nested` we'll enter `LibA.A` type which contains `B` struct. However, we don't set namespace to `LibA`, and will instead try to resolve `B` as item of `LibB`, which would fail.
I've updated `resolve_custom_types` fn to use custom `Resolver` visitor which keeps track of namespace, updates it before entering a type from another namespace and resets it to previous value after type is processed.
> fix(sol-macro): namespaced custom type resolution

- crates/primitives/src/signature/parity.rs
- crates/primitives/src/signature/sig.rs
To achieve https://github.com/paradigmxyz/reth/issues/10750 and replace reth Signature type by alloy one, 
The following is needed:
- impl Default for Parity
- impl Hash and Default for Signature
- add as_hex_bytes() and size() to Signature
I also moved some unit tests from reth to alloy.
> feat: prepare reth Signature migration to alloy

- crates/sol-macro-expander/src/expand/event.rs
- crates/sol-macro-expander/src/expand/mod.rs
- crates/sol-types/src/types/event/mod.rs
- crates/sol-types/tests/macros/sol/mod.rs
- crates/syn-solidity/src/item/event.rs
- crates/syn-solidity/src/type/mod.rs
Currently we're determining whether an indexed parameter is encoded as a hash (B256) by checking whether it is abi-dynamic. However this:
1. does not account for custom types, so UDVTs are treated as a hash when they shouldn't;
2. is not entirely correct as it will accept elementary fixed arrays such as `address[2]`.
This is fixed by accounting for custom types and using `is_value_type` instead of whether it is ABI-dynamic. The [Solidity ABI spec](https://docs.soliditylang.org/en/latest/abi-spec.html#events) states:
> For all types of length at most 32 bytes, the EVENT_INDEXED_ARGS array contains the value directly, padded or sign-extended (for signed integers) to 32 bytes, just as for regular ABI encoding. However, for all “complex” types or types of dynamic length, including all arrays, …
> fix(sol-macro): correctly determine whether event parameters are hashes

- Cargo.toml
- crates/core/Cargo.toml
- crates/primitives/Cargo.toml
- crates/primitives/src/lib.rs
- crates/primitives/src/utils/mod.rs
Adds a new feature `sha3-keccak` to `alloy-primitives` that when enabled, uses `sha3` for Keccak. This can be desirable as in some cases `sha3` is faster.
This feature is added in a completely backward-compatible way: `tiny-keccak` is still the default, and downstream libs/apps will _not_ suddenly start using `sha3` by just doing `cargo update`.
> feat: support Keccak with sha3

- crates/sol-macro-expander/src/expand/event.rs
- crates/sol-types/src/errors.rs
- crates/sol-types/src/types/event/mod.rs
- crates/sol-types/src/types/event/topic_list.rs
- crates/sol-types/tests/macros/sol/mod.rs
Fixes https://github.com/alloy-rs/core/issues/589
> fix(sol-types): check signature in SolEvent if non-anonymous

- crates/dyn-abi/src/eip712/typed_data.rs
- crates/primitives/src/bits/macros.rs
- crates/primitives/src/bits/serde.rs
Partially closes https://github.com/foundry-rs/foundry/issues/8715
We want to serialize Address type in checksum format. 
Solution is to implement a custom serialization function for `Address` type. 
I ran into some issues: 
1) The `impl_serde` macro conflicts with `impl Serialize for Address` (`Address` is wrapped with the `wrap_fixed_bytes` macro which calls `impl_serde`), so I added a workaround in `impl_serde` to bypass `Address` type. Another solution would be to just move the impl directly into the macro- if preferred. 
2) There's another type `EIP712Domain` which uses the type `Address`, I wanted to double check that it is okay for this to also be serialized in checksum format, I added another unit test to make it explicit.
> Add custom serialization for Address

- crates/json-abi/src/param.rs
- crates/json-abi/src/to_sol.rs
- crates/json-abi/tests/abi.rs
- crates/json-abi/tests/abi/DelegationManager.json
- crates/json-abi/tests/abi/DelegationManager.sol
- crates/sol-types/tests/macros/sol/json.rs
- crates/syn-solidity/tests/contracts.rs
Ref https://github.com/alloy-rs/core/issues/744
> fix(json-abi): correct to-sol for UDVT arrays in structs

- crates/primitives/src/map/fixed.rs
- crates/primitives/src/map/mod.rs
Temporary fix until https://github.com/rust-lang/rustc-hash/pull/52 is released.
> fix(primitives): make sure DefaultHashBuilder implements Clone

- crates/primitives/src/map/mod.rs
They don't really pull their weight when we have a default hasher, and I'm not planning on adding more aliases for each new hasher added to the module. Instead just keep the exports of the implementation and hasher.
> chore(primitives): remove Fx* aliases

- crates/json-abi/src/internal_type.rs
Fixes lint warnings for `alloy-json-abi`.
> Fix lint `alloy-json-abi`

- crates/primitives/src/bits/fixed.rs
- crates/primitives/src/signature/sig.rs
Fixes lint warnings for `alloy-primitives`.
> Fix lint `alloy-primitives`

- crates/primitives/Cargo.toml
- crates/primitives/src/sealed.rs
Reduce LOC for boilerplate code
Removes manual `Deref` impl in favour of `derive_more::Deref`
> Derive `Deref` for `Sealed<T>`

- crates/primitives/src/sealed.rs
`Arbitrary` is required trait bound for reth integration of `Sealed<T>`. Ref https://github.com/paradigmxyz/reth/issues/11123.
Derives `Arbitrary` for `Sealed<T>`.
> Derive `Arbitrary` for `Sealed<T>`

- Cargo.toml
- crates/primitives/Cargo.toml
- crates/primitives/src/map/fixed.rs
- crates/primitives/src/map/mod.rs
- tests/core-sol/src/lib.rs
This is the default hasher in hashbrown 0.15
> feat(primitives): add and use foldhash as default hasher

- crates/primitives/src/sealed.rs
`Default` is required trait bound for reth integration of `Sealed<T>`. Ref https://github.com/paradigmxyz/reth/issues/11123.
Derives `Default` for `Sealed<T>`.
> feat: add `Default` for `Sealed<T>`

- crates/dyn-abi/src/eip712/typed_data.rs
- crates/primitives/src/bits/macros.rs
- crates/primitives/src/bits/serde.rs
Reverts alloy-rs/core#742
this has been received badly and also messes a lot with rpc responses, making it harder to add cross client solutions.
> Revert "Add custom serialization for Address"

- crates/primitives/src/lib.rs
- crates/primitives/src/log/mod.rs
copied from
https://github.com/paradigmxyz/reth/blob/33d5eb322d32134c0875219f6e562824fbeca87e/crates/primitives-traits/src/log.rs#L4-L14
this only uses primitive types and can live here
ref https://github.com/alloy-rs/op-alloy/pull/165#pullrequestreview-2358347227
> feat: add logs_bloom

- crates/primitives/Cargo.toml
Fixes https://github.com/alloy-rs/core/issues/767
> fix: don't enable foldhash by default

- crates/primitives/src/postgres.rs
The `FromSql`/`ToSql` implementations for the Signed type didn't properly account for signs when dealing with the `NUMERIC` type. This PR addresses it. Check out the screenshot below for an example.
> fix: properly account for sign in pg to/from sql implementation for signed

- crates/primitives/src/sealed.rs
Was working on https://github.com/alloy-rs/alloy/pull/1485 and it seemed like there were a few holes in the API
this is a breaking change as it flattens the serde object
> feat: expand Seal api

- crates/core/Cargo.toml
- crates/primitives/Cargo.toml
- crates/primitives/src/map/mod.rs
Address all concerns raised in https://github.com/alloy-rs/core/pull/771#issuecomment-2424120800. This is the default hasher in hashbrown 0.15, it's better to make the fix in foldhash than here.
> fix: re-enable foldhash by default, but exclude it from zkvm

- crates/json-abi/src/abi.rs
You have made just a small mistake.
Replace `account` with `address` type because there is no account type in solidity.
Easy to understand!
> docs: fix param type in example comment

- crates/primitives/src/log/mod.rs
Following #775, this implements `DerefMut` for `Log<T>` so that the methods taking `&mut self` won't have compilation errors.
Thanks @mattsse for pointing out that, this can be workarounded by accessing `log.data` directly.
As above.
> Implement `DerefMut` for `Log<T>`

- crates/primitives/src/lib.rs
- crates/primitives/src/signature/mod.rs
- crates/primitives/src/signature/parity.rs
- crates/primitives/src/signature/primitive_sig.rs
- crates/primitives/src/signature/utils.rs
Right now we use `Parity` enum for parity value in signature: https://github.com/alloy-rs/core/blob/9c53778e4d40a8ac5b7d3e36221efc1d79fec050/crates/primitives/src/signature/parity.rs#L10-L17
Because of it containing EIP-155 related variants it basically captures transaction-related logic which does not belong to primitives and results in inconsistencies and need for dynamic checks. e.g https://github.com/alloy-rs/alloy/pull/1305 https://github.com/alloy-rs/core/issues/705 https://github.com/alloy-rs/alloy/issues/1510
Primitive signature representation in context of Ethereum is `(U256,U256,bool)`, this PR changes `Signature` to have this structure and leaving specialized parity encoding to types holding signatures and having enough context to perform correct encoding.
At this point in any …
> refactor: use simple boolean for parity in signature

- crates/json-abi/src/item.rs
- crates/json-abi/src/param.rs
- crates/json-abi/src/utils.rs
Inline macros where they're not necessary, clean up implementations.
> chore(json-abi): clean up utils

- crates/primitives/src/signature/parity.rs
- crates/primitives/src/signature/sig.rs
https://github.com/alloy-rs/alloy/pull/1578
https://github.com/alloy-rs/alloy/pull/1581
Add a convenience function for determining if a signature has an EIP-155 value
> feat: add has_eip155_value convenience function to signature

- crates/primitives/src/lib.rs
- crates/primitives/src/signature/mod.rs
- crates/primitives/src/signature/parity.rs
- crates/primitives/src/signature/primitive_sig.rs
- crates/primitives/src/signature/sig.rs
- crates/primitives/src/signature/utils.rs
> Revert "chore: replace Signature with PrimitiveSignature"

- crates/primitives/src/signature/primitive_sig.rs
Geth responds with `v` for EIP-1559 transactions. This PR updates default serde impl for `PrimitiveSignature` to accept `v`  in place of `yParity`. Only 0/1 values for v would get correctly deserialized.
Additionaly, we now always serialize both `v` and `yParity` for compatibility as this is done in reth: https://github.com/paradigmxyz/reth/blob/bd8c4eceb20c39c6e501d06cf906469329340bb9/crates/rpc/rpc-types-compat/src/transaction/signature.rs#L29
> fix(serde): add alias `v` for `yParity`

- crates/primitives/src/sealed.rs
`flatten` is wrong here, and making it always (de)serialize as hash allows us to reuse it for transactions and blocks.
> fix: `Sealed::hash` serde

- CHANGELOG.md
- Cargo.toml
- crates/core/CHANGELOG.md
- crates/dyn-abi/CHANGELOG.md
- crates/json-abi/CHANGELOG.md
- crates/primitives/CHANGELOG.md
- crates/sol-macro-expander/CHANGELOG.md
- crates/sol-macro-input/CHANGELOG.md
- crates/sol-macro/CHANGELOG.md
- crates/sol-type-parser/CHANGELOG.md
- crates/sol-types/CHANGELOG.md
- crates/syn-solidity/CHANGELOG.md
> chore: release 0.8.12

- crates/dyn-abi/src/dynamic/call.rs
The `DynSolCall` implementation was not exposing the `returns` field. 
Add a method to get the `returns` field
> feat: expose `returns` field for `DynSolCall` type

- crates/primitives/src/signature/sig.rs
Before https://github.com/alloy-rs/core/pull/719 Signature fields were public and it was possible to create `Signature { r, s, odd_y_parity }` in a const context.
Make `Signature::new` a const fn.
> Make Signature::new a const fn

- crates/sol-macro-expander/src/expand/var_def.rs
- crates/sol-types/tests/macros/sol/mod.rs
Fixes https://github.com/alloy-rs/core/issues/811
Logic was implemented slightly incorrectly from https://github.com/ethereum/solidity/blob/9d7cc42bc1c12bb43e9dccf8c6c36833fdfcbbca/libsolidity/ast/Types.cpp#L2852
This is a breaking change for the generated return type structs of some mapping getters, but it should be fine since it was incorrect before too
> fix(sol-macro): expand all getter return types

- crates/primitives/src/log/mod.rs
adds `AsRef<Self>` for `Log`
this is useful for because we have layered logs types (rpc::Log) and we'd like to have `impl TxReveipt where T: AsRef<Log>` 
currently we use `Borrow` but this is semantically incorrect:
>Borrow also requires that Hash, Eq and Ord for a borrowed value are equivalent to those of the owned value. For this reason, if you want to borrow only a single field of a struct you can implement AsRef, but not Borrow.
https://doc.rust-lang.org/std/convert/trait.AsRef.html
> chore: asRef for Log

- crates/sol-macro-expander/src/expand/contract.rs
- crates/sol-macro-expander/src/expand/enum.rs
- The `sol!` macro cannot be used in projects with strict unsafe code policies.
- The current unsafe implementation of `abi_decode_raw` is not efficient: binary search (`O(log n)`) is slower than a simple jump table (`O(1)` or `O(n)` at worst, for e.g. [compare the MIR/asm output](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=0b66ad61f00025c8e9c1e4a1a93a2ab2)).
- Switch `abi_decode_raw` to use a constant jump table instead of a runtime binary search.
- Generate safe code to convert between enum variants and `u8` statically.
- Make the `as_u8` function constant.
- Additionally, allow `clippy::empty_structs_with_brackets` in the generated code.
> Remove unsafe code from macro expansions

- crates/primitives/src/lib.rs
- crates/primitives/src/signature/mod.rs
- crates/primitives/src/signature/parity.rs
- crates/primitives/src/signature/sig.rs
It might be better to notify users in advance before completely migrating from Signature to PrimitiveSignature.
> chore: mark `Signature` as deprecated

- Cargo.toml
- crates/primitives/src/map/mod.rs
Linked PR was released in 2.1.0.
> chore(primitives): remove rustc-hash workaround

- crates/primitives/src/sealed.rs
more convenient than `clone().unseal()`
> chore: add clone_inner

- crates/primitives/src/signature/primitive_sig.rs
Closes https://github.com/alloy-rs/core/issues/831
This still does not allow non-boolean values for `yParity` which should be fine I believe
> fix: allow non-boolean v values for PrimitiveSignature

- Cargo.toml
- crates/primitives/src/map/mod.rs
As of [v.0.1.4](https://github.com/orlp/foldhash/compare/v0.1.3...v0.1.4), the `foldhash` dependency has fixed the issue on `zkvm` targets originally reported in https://github.com/alloy-rs/core/issues/767. As such, the implemented workaround is no longer necessary as of this release and has been removed in this PR.
> fix: re-enable foldhash on zkvm

- crates/dyn-abi/src/coerce.rs
- crates/dyn-abi/src/error.rs
implement and close https://github.com/alloy-rs/core/issues/816
> feat(dyn-abi): support parse scientific number

- Cargo.toml
- crates/primitives/Cargo.toml
- crates/primitives/src/map/mod.rs
re-export rayon traits implementations depends on which HashMap implementation is used
> feat: re-export rayon traits implementations

- crates/sol-macro-expander/src/expand/contract.rs
- crates/sol-macro-expander/src/expand/event.rs
- crates/sol-macro-expander/src/expand/mod.rs
- crates/sol-macro-expander/src/expand/struct.rs
- crates/sol-macro-expander/src/expand/to_abi.rs
- crates/sol-macro-expander/src/expand/ty.rs
- crates/sol-macro-expander/src/expand/udt.rs
- crates/sol-types/tests/macros/sol/mod.rs
- crates/syn-solidity/src/expr/mod.rs
- crates/syn-solidity/src/item/mod.rs
- crates/syn-solidity/src/lit/number.rs
- crates/syn-solidity/src/type/array.rs
Fixes https://github.com/alloy-rs/core/issues/802.
Review with whitespace disabled.
> feat(sol-macro): evaluate array sizes

- crates/primitives/src/map/fixed.rs
- crates/primitives/src/map/mod.rs
- tests/core-sol/src/lib.rs
Fixed in the latest foldhash release.
> test: re-enable miri on foldhash

- crates/sol-macro-expander/src/expand/contract.rs
- crates/sol-macro-expander/src/expand/event.rs
- crates/sol-macro-expander/src/expand/mod.rs
- tests/core-sol/src/lib.rs
Closes https://github.com/alloy-rs/core/issues/588.
> test(sol-macro): add a test for missing_docs

- crates/primitives/src/lib.rs
This should've never been public, since it only contains one public item (the `hex!` macro) which we already re-export at the root.
> docs: hide hex_literal export

- .github/workflows/ci.yml
- Cargo.toml
- crates/core/Cargo.toml
- crates/dyn-abi/Cargo.toml
- crates/json-abi/Cargo.toml
- crates/primitives/Cargo.toml
- crates/sol-macro-expander/Cargo.toml
- crates/sol-macro-input/Cargo.toml
- crates/sol-macro/Cargo.toml
- crates/sol-type-parser/Cargo.toml
- crates/sol-types/Cargo.toml
- crates/syn-solidity/Cargo.toml
- [--generate-link-to-definition](https://doc.rust-lang.org/rustdoc/unstable-features.html#--generate-link-to-definition-generate-links-on-types-in-source-code)
- [--show-type-layout](https://doc.rust-lang.org/rustdoc/unstable-features.html#--show-type-layout-add-a-section-to-each-types-docs-describing-its-memory-layout)
- `--cfg docsrs` [is guaranteed to be enabled](https://docs.rs/about/builds#detecting-docsrs)
- `workspace.metadata` is not read
> docs: enable some useful rustdoc features on docs.rs

- crates/json-abi/src/param.rs
Adds `Param.name()` for accessing the parameter name.
There is already `Param.name` field but it is hidden in docs.
> feat(json-abi): add Param.name() accessor

- crates/primitives/src/sealed.rs
add a `Sealed<&T>::cloned` fn, similar to `Option::cloned`
> feat: add Sealed::cloned

- crates/sol-macro-expander/src/expand/mod.rs
We ran into issues with the resolve limit when working on our migration from ethers-rs to alloy in
https://github.com/EspressoSystems/espresso-sequencer/pull/2456
The specific command we run is
forge bind --skip test --skip script --libraries \
contracts/src/libraries/PlonkVerifier.sol:PlonkVerifier:0xB0bfeE1e1A7Ef832149EDe013B34AD6248176385 \
--alloy --contracts ./contracts/src/ --crate-name \
contract-bindings-alloy --bindings-path contract-bindings-alloy
--select \
"^LightClient$|^LightClientArbitrum$|^LightClientStateUpdateVK$|^FeeContract$|PlonkVerifier$|^ERC1967Proxy$|^LightClientMock$|^LightClientStateUpdateVKMock$|^PlonkVerifier2$|^PermissionedStakeTable$"
--overwrite --force
And it outputs
[⠊] Compiling...
[⠔] Compiling 36 files with Solc 0.8.28
[⠒] Solc 0.8.28 finished in 1.53s …
> feat(`sol-macro-expander`): increase resolve limit to 128

- crates/primitives/src/bits/fixed.rs
- crates/primitives/src/bits/macros.rs
Both `OsRng` and `ThreadRng` implement `CryptoRng`, and guarantee that they're cryptographically secure.
> docs(primitives): `random` functions are cryptographically secure

- crates/primitives/src/common.rs
adds a consuming into_to call
preventing a copy when used like `.kind().to().copied()`
> feat: add TxKind::into_to

- crates/primitives/src/bytes/mod.rs
Some methods of the `Bytes` struct call the underlying implementation from the `bytes` crate but their docs do not outline that they might panic.
Added documentation to note which methods may panic inheriting the docs from the `bytes` crate
> docs(primitives): report some Bytes methods may panic

- crates/primitives/src/signature/primitive_sig.rs
This representation of the signature is slightly more compact and can be useful for on-chain signature verification as it saves calldata.
Closes #873 
Add a helper to generate such a representation
> feat: erc2098 signature representation

- crates/sol-types/src/impl_core.rs
- crates/sol-types/src/types/data_type.rs
Using `as_flattened` lets us simplify `stv_eip712_data_word` for fixed-size arrays.
> chore: simplify uninit_array usage

- crates/primitives/src/signature/error.rs
- crates/primitives/src/signature/primitive_sig.rs
- crates/primitives/src/signature/utils.rs
Add `normalized_s`, `from_raw`, and simplify existing implementations.
> feat(primitives): add some more utility methods to PrimitiveSignature

- crates/sol-macro-expander/src/expand/function.rs
- crates/sol-macro/doctests/function_like.rs
- crates/sol-types/tests/macros/sol/json.rs
- crates/sol-types/tests/macros/sol/mod.rs
Closes #880 
Stacked over #883 
```rust
sol! {
function totalSupply() returns (uint256);
function balanceOf(address) returns (uint256);
}
// Unit struct
pub struct totalSupplyCall;
// Tuple struct
pub struct balanceOfCall(pub Address); // Loses name of the param
// Previously, 
pub struct totalSupplyCall {};
pub struct balanceOfCall { owner: Address }; 
```
- Bindings for calls with 2 or more params left unchanged.
> feat(`sol!`)!: gen unit/tuple structs for call types with 0/1 param

- crates/sol-macro-input/Cargo.toml
- crates/sol-macro-input/src/attr.rs
- crates/sol-macro-input/src/input.rs
- crates/sol-macro/doctests/json.rs
- crates/sol-macro/src/lib.rs
- crates/sol-types/tests/macros/sol/json.rs
- deny.toml
Use [macro-string](https://docs.rs/macro-string) to allow standard library macros such as concat!, env!, and include_str! wherever a string literal is expected in the macro input.
Closes https://github.com/alloy-rs/core/issues/738.
Closes https://github.com/alloy-rs/core/issues/659.
> feat(sol-macro): allow standard library macros for string literals

- crates/sol-macro-expander/src/expand/event.rs
- crates/sol-types/tests/macros/sol/mod.rs
Closes #879 
Stacked over #883 
- If event does not contain any params, generate a unit struct instead of an empty struct.
```rust
sol! {
event Empty();
}
// New 
pub struct Empty;
// Previous 
pub struct Empty {};
```
Bindings for events with params remain unchanged.
> fix(`sol!`)!: gen unit struct for no param events

- Cargo.toml
- crates/dyn-abi/Cargo.toml
- crates/dyn-abi/benches/types.rs
- crates/primitives/Cargo.toml
- crates/primitives/src/bits/fixed.rs
- crates/primitives/src/bits/macros.rs
Adds `try*` versions for the `_with` functions which use `TryRngCore`.
> chore(deps)!: bump getrandom to 0.3, rand to 0.9

- crates/syn-solidity/src/ident/mod.rs
- tests/core-sol/src/lib.rs
Closes #902 
Rust does not accept the raw identifier for `self` i.e `r#self`. See: https://internals.rust-lang.org/t/raw-identifiers-dont-work-for-all-identifiers/9094/4
- Map `self` to `this`.
```rust
sol! {
function something(address self) returns (uint256);  // Previously failed to compile
}
// Now generates
pub struct somethingCall { this: Address };
```
> fix(`sol-expander`): map `self` to `this` in codegen

- crates/sol-macro-expander/src/expand/contract.rs
- crates/sol-macro/src/lib.rs
After #884, call types are expanded depending on the number of params.
This change isn't propagated to `rpc` expansion code where call_builder is called.
- Generate the correct call struct like #884
- Pass it to `call_builder`
> fix(`sol!`): pass correct call_struct to call_builder in expansion

- crates/primitives/src/bytes/mod.rs
Remove the `From<String> for Bytes` implementation to allow using `Bytes` with `clap` by default.
Reference: https://docs.rs/clap/latest/clap/macro.value_parser.html
`From<String>` takes higher precedence than `FromStr`.
> feat(primitives): remove `From<String> for Bytes`

- crates/sol-macro-expander/src/expand/function.rs
- crates/sol-types/src/types/function.rs
- crates/sol-types/tests/macros/sol/mod.rs
Changes `SolCall::abi_encode_returns` to accept `Self::Return` instead of the tuple.
Fixes https://github.com/alloy-rs/core/issues/536.
> feat(sol-macro)!: improve call return encoding

- crates/primitives/src/signature/primitive_sig.rs
Port https://github.com/alloy-rs/core/pull/810 from Signature to PrimitiveSignature (no idea how it was lost).
> Make PrimitiveSignature::new a const fn

- crates/primitives/src/sealed.rs
- Introduced a new `hash_ref()` method on `Sealed<T>` to expose a reference to the internal `seal` hash.
- This addition enables consumers to access the hash without incurring a copy, which is useful when only a reference is needed.
This change supports [reth#15250](https://github.com/paradigmxyz/reth/pull/15250), where `OpTxEnvelope::Deposit` will implement `SignedTransaction`. Since the `hash()` method on `Sealed<TxDeposit>` returns by value, `hash_ref()` allows returning a borrowed hash to satisfy trait requirements (`&TxHash`)
> chore: add hash_ref function to sealed.rs

- crates/primitives/src/bits/macros.rs
- tests/core-sol/Cargo.toml
- tests/core-sol/src/lib.rs
`wrap_fixed_bytes` can't be used without `bytes` as a dependency.
there's similar issue with `derive_more` but I'm unsure how we can handle this given that it seems to rely on `derive_more` being available internally
> fix: do not rely on bytes dependency in `wrap_fixed_bytes!`

- crates/primitives/src/bits/fixed.rs
- crates/primitives/src/lib.rs
Currently, the code for generating random `FixedBytes` primitives is incorrect. It calls `assume_init` directly on an uninitialized array, which invokes immediate undefined behavior.
Note that it doesn't matter that we technically never explicitly read from the array before randomizing. An uninitialized byte array is always invalid and violates Rust rules. Refer to the [docs for MaybeUninit](https://doc.rust-lang.org/core/mem/union.MaybeUninit.html).
We should follow the documentation of [`MaybeUninit::assume_init`](https://doc.rust-lang.org/std/mem/union.MaybeUninit.html#method.assume_init) and make sure every element was written to. Since we're initializing arrays, I used `[MaybeUninit<u8>; N]` (idiomatic for Rust), together with `array_assume_init` (currently unstable, I added a …
> fix(primitives): Remove undefined behavior in FixedBytes

- Cargo.toml
- crates/primitives/CHANGELOG.md
- crates/primitives/Cargo.toml
- crates/primitives/src/bits/fixed.rs
- crates/primitives/src/bits/macros.rs
- crates/primitives/src/diesel.rs
- crates/primitives/src/lib.rs
- crates/primitives/src/signature/sig.rs
This PR adds diesel support for `alloy-primitives`, covering the following:
- add diesel dep, gated behind new `diesel` feature
- bump ruint dep by a patch version to include its diesel support, also gated behind the `diesel` feature
- manually implementing diesel-related traits where needed, similar to [the PR adding diesel support to ruint](https://github.com/recmo/uint/pull/404)
- macro-deriving diesel-related traits where possible, for `FixedBytes`, `Address` (via the macro that creates it), and `PrimitiveSignature`
- `PrimitiveSignature` encoded via erc2098
I had most of this code already written for another project and wanted to contribute it upstream. I noticed issue #876 had some activity but didn't see any indications of a PR so I hope this doesn’t overlap with anyone else’s …
> feat(primitives): supporting diesel @ 2.2

- crates/sol-macro-expander/src/expand/ty.rs
The following code:
```rust
alloy_sol_types::sol! {
struct Struc {
uint256[11 % 8] arr;
}
}
let _ = Struc {
arr: [Default::default(); 11 % 8],
};
```
did not compile with the following error:
```
error[E0308]: mismatched types
--> src\main.rs:9:10
|
9 |     arr: [Default::default(); 11 % 8],
|          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected an array with a size of 1, found one with a size of 3
|
= note: expected array `[alloy_sol_types::private::Uint<256, 4>; 1]`
found array `[alloy_sol_types::private::Uint<256, 4>; 3]`
```
> fix: array size evaluation with modulo operator

- crates/primitives/src/utils/mod.rs
- crates/primitives/src/utils/units.rs
> feat: added format_units_with

- crates/dyn-abi/src/eip712/parser.rs
- crates/dyn-abi/src/eip712/typed_data.rs
- crates/sol-types/src/types/struct.rs
Ref https://github.com/alloy-rs/alloy/issues/2349
> docs: improve eip712 docs and discoverability

- crates/primitives/src/bits/address.rs
Add `.create_eof` method to Address for EOF contract address calculation
closes #924
Implemented `.create_eof` method following the provided algorithm and added tests.
> feat(primitives): add `Address::create_eof`

- crates/sol-types/tests/macros/sol/eip712.rs
- crates/syn-solidity/src/variable/mod.rs
fixes #948
When calculating the eip712 type string for example struct
```sol
interface IParentInterfaceA {
struct ParentStructA {
uint256 numberA;
}
}
interface IParentInterfaceB {
struct ParentStructB {
uint256 numberB;
}
}
interface IMyInterface is IParentInterfaceA, IParentInterfaceB {
struct MyStruct {
ParentStructA structA;
ParentStructB structB;
}
}
```
Expected: `"MyStruct(ParentStructA structA, ParentStructB structB)ParentStructA(uint256 numberA)ParentStructB(uint256 numberB)"`
Incorrect: `"MyStruct(IParentInterfaceA.ParentStructA structA, IParentInterfaceB.ParentStructB structB)ParentStructA(uint256 numberA)ParentStructB(uint256 numberB)"`
This PR fixes the problem by removing the interface prefix string while calculating the eip712 type string
> fix: eip712 string interface prefix

- crates/sol-macro/doctests/events.rs
- crates/sol-types/src/types/event/mod.rs
closes #955 
There was no `decode_log_validate` method and user had to call `decode_raw_log_validate` manually
Added `decode_log_validate` and `decode_log_data_validate` methods
> feat: added `decode_log_validate` method

- crates/dyn-abi/Cargo.toml
- crates/dyn-abi/src/eip712/parser.rs
- crates/dyn-abi/src/eip712/resolver.rs
- crates/dyn-abi/src/eip712/typed_data.rs
- crates/sol-type-parser/Cargo.toml
- crates/sol-type-parser/src/ident.rs
- crates/sol-type-parser/src/root.rs
- crates/sol-type-parser/src/stem.rs
- crates/sol-type-parser/src/tuple.rs
- crates/sol-type-parser/src/type_spec.rs
ref:
- https://github.com/foundry-rs/foundry/issues/10765
`:` in names causing `TypeSpecifier` identifier parsing to fail, not sure how this should be solved.
there are two aspects to this issue, is a `A:B` entry valid, and how should this be resolved and hashed
> fix: custom eip712 parsing allowing `:`

- crates/dyn-abi/src/dynamic/value.rs
```rs
let uint = U256::ZERO;
let address = Address::ZERO;
let word = B256::ZERO;
input(uint); // works
input(address); // works
input(word); // the trait bound `dynamic::value::DynSolValue: std::convert::From<alloy_primitives::FixedBytes<32>>` is not satisfied
fn input(v: impl Into<DynSolValue>) {}
```
Implemented conversion from `Word` for `DynSolValue`.
> Implement conversion from `Word` for `DynSolValue`

- crates/sol-macro-expander/src/expand/contract.rs
closes https://github.com/foundry-rs/foundry/issues/11180
two edge cases with `provider`
we add additional function names to the instance and need to check that these don't conflict
also, having `struct provider;` messes with `provider:P` arguments -.- so I renamed to `__provider`
with this this now compiles.
no function changes expected, renaming these functions is fine, didn't work before, hence the issue.
> fix(rpc): check reserved function names

- crates/primitives/src/map/mod.rs
Rust standard library and hashbrown `Entry` types have different generics. Re-export std's ones which don't have S, and provide defaults for S for hashbrown.
Ideally we would have type aliases for std with an `S` that is unused, but that is a hard error on type aliases, and I don't feel like re-implementing the entire Entry API when this is good enough.
cc @Rjected 
Fixes https://github.com/alloy-rs/core/issues/942.
> fix(primitives): re-export correct `Entry` types

- Cargo.toml
- crates/primitives/Cargo.toml
- crates/primitives/src/bits/borsh.rs
- crates/primitives/src/bits/macros.rs
- crates/primitives/src/bits/mod.rs
- crates/primitives/src/bytes/borsh.rs
- crates/primitives/src/bytes/mod.rs
- crates/primitives/src/lib.rs
Close #992 
- Added borsh as a dependency in Cargo.toml files for the main crate and primitives.
- Implemented borsh serialization and deserialization macros in the primitives library.
- Implemented borsh serialization and deserialization for `FixedBytes`
> feat(primitives): add borsh support

- crates/sol-macro-expander/src/expand/contract.rs
The `enum` containers associated to contracts function calls, custom errors and events, don't implement the `Clone` trait while the underlying `struct`s do.
Having the `Clone` trait propagated at this higher level is generally useful.
Add `#[derive(Clone)]` where the containers are defined.
- No pre-existing test on which traits are implemented.
- No pre-existing documentation on which traits are implemented in the custom containers.
- Not a breaking change
> feat(sol-macro-expander): add `Clone` trait to enum contracts containers

- crates/sol-macro-expander/src/expand/contract.rs
- crates/sol-macro-expander/src/expand/function.rs
- crates/sol-macro-input/src/attr.rs
- crates/sol-types/tests/macros/sol/mod.rs
Inherit `#[sol(...)]` from contract when expanding that contract's attributes.
> feat(sol-macro): inherit attributes from contract

- crates/sol-macro-expander/src/expand/error.rs
- crates/sol-macro-expander/src/expand/event.rs
- crates/sol-macro-expander/src/expand/function.rs
- crates/sol-macro-expander/src/expand/to_abi.rs
- crates/sol-macro-expander/src/verbatim.rs
- crates/sol-types/src/lib.rs
- crates/sol-types/tests/macros/sol/abi.rs
Use the `#item::abi()` functions instead of re-expanding every function inside of the contract's ABI. Also expand it lazily with a static array of function pointers to avoid inlining
> perf(sol-macro): improve abi expansion

- crates/primitives/src/sqlx.rs
The Unsigned a.k.a `U256`, `U512` ... types already do impl sqlx Traits which enables crate users to directly pass the said types into sqlx queries,
Once I tried to do the same for Signed types I realized that these traits are missing in `sqlx` crate feature, even though the underlying type is the same, so that motivated me to impl these traits.
impl Type, Encode, Decode traits under the sqlx feature that is already existing.
> feat: Add Sqlx Traits for `Signed` Type

- crates/sol-macro-expander/src/expand/contract.rs
- crates/sol-macro-expander/src/expand/udt.rs
This triggers an `unused_attributes` warning in the latest stable version.
```rust
warning: `#[automatically_derived]` attribute cannot be used on inherent impl blocks
--> src/main.rs:4:1
|
4 | #[automatically_derived]
| ^^^^^^^^^^^^^^^^^^^^^^^^
|
= warning: this was previously accepted by the compiler but is being phased out; it will become a hard error in a future release!
= help: `#[automatically_derived]` can only be applied to trait impl blocks
= note: `#[warn(unused_attributes)]` (part of `#[warn(unused)]`) on by default
```
> fix(sol-macro): remove #[automatically_derived] from non-trait impls

- crates/primitives/src/postgres.rs
Closes https://github.com/alloy-rs/core/pull/1010
> chore: tweak postgres.rs

- crates/primitives/Cargo.toml
- crates/primitives/src/common.rs
Close #1021
- Enable derive feature on Borsh.
- Add Borsh support for `TxKind`
> feat(primitives): Add Borsh support for `TxKind`

- crates/syn-solidity/src/attribute/mod.rs
- crates/syn-solidity/src/kw.rs
- crates/syn-solidity/tests/contracts/TransientStorage.sol
Closes https://github.com/alloy-rs/core/issues/1024
Allow `alloy_sol_macro` to parse `transient` keyword that has been introduced in `0.28.8`.
Add transient as a keyword in the storage sub-category
Side question: Is the Yul parsing still maintained ? If yes, is it ok to add `tstore` and `tload` opcodes ?
> feat(sol-macro): add transient storage keyword support
